// <auto-generated>
/*
 * Whisparr
 *
 * Whisparr API docs - The v3 API docs apply to both v2 versions of Whisparr. Some functionality may only be available in v2 of the Whisparr application.
 *
 * The version of the OpenAPI document: 3.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Whisparr2.Net.Client;

namespace Whisparr2.Net.Model
{
    /// <summary>
    /// EpisodeResourcePagingResource
    /// </summary>
    public partial class EpisodeResourcePagingResource : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EpisodeResourcePagingResource" /> class.
        /// </summary>
        /// <param name="page">page</param>
        /// <param name="pageSize">pageSize</param>
        /// <param name="sortKey">sortKey</param>
        /// <param name="sortDirection">sortDirection</param>
        /// <param name="totalRecords">totalRecords</param>
        /// <param name="records">records</param>
        [JsonConstructor]
        public EpisodeResourcePagingResource(Option<int?> page = default, Option<int?> pageSize = default, Option<string?> sortKey = default, Option<SortDirection?> sortDirection = default, Option<int?> totalRecords = default, Option<List<EpisodeResource>?> records = default)
        {
            PageOption = page;
            PageSizeOption = pageSize;
            SortKeyOption = sortKey;
            SortDirectionOption = sortDirection;
            TotalRecordsOption = totalRecords;
            RecordsOption = records;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of SortDirection
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<SortDirection?> SortDirectionOption { get; private set; }

        /// <summary>
        /// Gets or Sets SortDirection
        /// </summary>
        [JsonPropertyName("sortDirection")]
        public SortDirection? SortDirection { get { return this.SortDirectionOption.Value; } set { this.SortDirectionOption = new(value); } }

        /// <summary>
        /// Used to track the state of Page
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> PageOption { get; private set; }

        /// <summary>
        /// Gets or Sets Page
        /// </summary>
        [JsonPropertyName("page")]
        public int? Page { get { return this.PageOption.Value; } set { this.PageOption = new(value); } }

        /// <summary>
        /// Used to track the state of PageSize
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> PageSizeOption { get; private set; }

        /// <summary>
        /// Gets or Sets PageSize
        /// </summary>
        [JsonPropertyName("pageSize")]
        public int? PageSize { get { return this.PageSizeOption.Value; } set { this.PageSizeOption = new(value); } }

        /// <summary>
        /// Used to track the state of SortKey
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SortKeyOption { get; private set; }

        /// <summary>
        /// Gets or Sets SortKey
        /// </summary>
        [JsonPropertyName("sortKey")]
        public string? SortKey { get { return this.SortKeyOption.Value; } set { this.SortKeyOption = new(value); } }

        /// <summary>
        /// Used to track the state of TotalRecords
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> TotalRecordsOption { get; private set; }

        /// <summary>
        /// Gets or Sets TotalRecords
        /// </summary>
        [JsonPropertyName("totalRecords")]
        public int? TotalRecords { get { return this.TotalRecordsOption.Value; } set { this.TotalRecordsOption = new(value); } }

        /// <summary>
        /// Used to track the state of Records
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<EpisodeResource>?> RecordsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Records
        /// </summary>
        [JsonPropertyName("records")]
        public List<EpisodeResource>? Records { get { return this.RecordsOption.Value; } set { this.RecordsOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EpisodeResourcePagingResource {\n");
            sb.Append("  Page: ").Append(Page).Append("\n");
            sb.Append("  PageSize: ").Append(PageSize).Append("\n");
            sb.Append("  SortKey: ").Append(SortKey).Append("\n");
            sb.Append("  SortDirection: ").Append(SortDirection).Append("\n");
            sb.Append("  TotalRecords: ").Append(TotalRecords).Append("\n");
            sb.Append("  Records: ").Append(Records).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="EpisodeResourcePagingResource" />
    /// </summary>
    public partial class EpisodeResourcePagingResourceJsonConverter : JsonConverter<EpisodeResourcePagingResource>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="EpisodeResourcePagingResourceJsonConverter" /> class.
        /// </summary>
        public EpisodeResourcePagingResourceJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="EpisodeResourcePagingResource" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override EpisodeResourcePagingResource Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> page = default;
            Option<int?> pageSize = default;
            Option<string?> sortKey = default;
            Option<SortDirection?> sortDirection = default;
            Option<int?> totalRecords = default;
            Option<List<EpisodeResource>?> records = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "page":
                            page = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "pageSize":
                            pageSize = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "sortKey":
                            sortKey = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "sortDirection":
                            sortDirection = new Option<SortDirection?>(JsonSerializer.Deserialize<SortDirection?>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "totalRecords":
                            totalRecords = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "records":
                            records = new Option<List<EpisodeResource>?>(JsonSerializer.Deserialize<List<EpisodeResource>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (page.IsSet && page.Value == null)
                throw new ArgumentNullException(nameof(page), "Property is not nullable for class EpisodeResourcePagingResource.");

            if (pageSize.IsSet && pageSize.Value == null)
                throw new ArgumentNullException(nameof(pageSize), "Property is not nullable for class EpisodeResourcePagingResource.");

            if (sortDirection.IsSet && sortDirection.Value == null)
                throw new ArgumentNullException(nameof(sortDirection), "Property is not nullable for class EpisodeResourcePagingResource.");

            if (totalRecords.IsSet && totalRecords.Value == null)
                throw new ArgumentNullException(nameof(totalRecords), "Property is not nullable for class EpisodeResourcePagingResource.");

            return new EpisodeResourcePagingResource(page, pageSize, sortKey, sortDirection, totalRecords, records);
        }

        /// <summary>
        /// Serializes a <see cref="EpisodeResourcePagingResource" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="episodeResourcePagingResource"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, EpisodeResourcePagingResource episodeResourcePagingResource, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, episodeResourcePagingResource, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="EpisodeResourcePagingResource" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="episodeResourcePagingResource"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, EpisodeResourcePagingResource episodeResourcePagingResource, JsonSerializerOptions jsonSerializerOptions)
        {
            if (episodeResourcePagingResource.PageOption.IsSet)
                writer.WriteNumber("page", episodeResourcePagingResource.PageOption.Value!.Value);

            if (episodeResourcePagingResource.PageSizeOption.IsSet)
                writer.WriteNumber("pageSize", episodeResourcePagingResource.PageSizeOption.Value!.Value);

            if (episodeResourcePagingResource.SortKeyOption.IsSet)
                if (episodeResourcePagingResource.SortKeyOption.Value != null)
                    writer.WriteString("sortKey", episodeResourcePagingResource.SortKey);
                else
                    writer.WriteNull("sortKey");

            if (episodeResourcePagingResource.SortDirectionOption.IsSet)
            {
                var sortDirectionRawValue = SortDirectionValueConverter.ToJsonValue(episodeResourcePagingResource.SortDirection!.Value);
                writer.WriteString("sortDirection", sortDirectionRawValue);
            }
            if (episodeResourcePagingResource.TotalRecordsOption.IsSet)
                writer.WriteNumber("totalRecords", episodeResourcePagingResource.TotalRecordsOption.Value!.Value);

            if (episodeResourcePagingResource.RecordsOption.IsSet)
                if (episodeResourcePagingResource.RecordsOption.Value != null)
                {
                    writer.WritePropertyName("records");
                    JsonSerializer.Serialize(writer, episodeResourcePagingResource.Records, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("records");
        }
    }
}
