// <auto-generated>
/*
 * Whisparr
 *
 * Whisparr API docs - The v3 API docs apply to both v2 versions of Whisparr. Some functionality may only be available in v2 of the Whisparr application.
 *
 * The version of the OpenAPI document: 3.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Whisparr2.Net.Client;

namespace Whisparr2.Net.Model
{
    /// <summary>
    /// Defines EpisodeHistoryEventType
    /// </summary>
    public enum EpisodeHistoryEventType
    {
        /// <summary>
        /// Enum Unknown for value: unknown
        /// </summary>
        Unknown,

        /// <summary>
        /// Enum Grabbed for value: grabbed
        /// </summary>
        Grabbed,

        /// <summary>
        /// Enum SeriesFolderImported for value: seriesFolderImported
        /// </summary>
        SeriesFolderImported,

        /// <summary>
        /// Enum DownloadFolderImported for value: downloadFolderImported
        /// </summary>
        DownloadFolderImported,

        /// <summary>
        /// Enum DownloadFailed for value: downloadFailed
        /// </summary>
        DownloadFailed,

        /// <summary>
        /// Enum EpisodeFileDeleted for value: episodeFileDeleted
        /// </summary>
        EpisodeFileDeleted,

        /// <summary>
        /// Enum EpisodeFileRenamed for value: episodeFileRenamed
        /// </summary>
        EpisodeFileRenamed,

        /// <summary>
        /// Enum DownloadIgnored for value: downloadIgnored
        /// </summary>
        DownloadIgnored
    }

    /// <summary>
    /// Converts <see cref="EpisodeHistoryEventType"/> to and from the JSON value
    /// </summary>
    public static class EpisodeHistoryEventTypeValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="EpisodeHistoryEventType"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static EpisodeHistoryEventType FromString(string value)
        {
            if (value.Equals("unknown"))
                return EpisodeHistoryEventType.Unknown;

            if (value.Equals("grabbed"))
                return EpisodeHistoryEventType.Grabbed;

            if (value.Equals("seriesFolderImported"))
                return EpisodeHistoryEventType.SeriesFolderImported;

            if (value.Equals("downloadFolderImported"))
                return EpisodeHistoryEventType.DownloadFolderImported;

            if (value.Equals("downloadFailed"))
                return EpisodeHistoryEventType.DownloadFailed;

            if (value.Equals("episodeFileDeleted"))
                return EpisodeHistoryEventType.EpisodeFileDeleted;

            if (value.Equals("episodeFileRenamed"))
                return EpisodeHistoryEventType.EpisodeFileRenamed;

            if (value.Equals("downloadIgnored"))
                return EpisodeHistoryEventType.DownloadIgnored;

            throw new NotImplementedException($"Could not convert value to type EpisodeHistoryEventType: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="EpisodeHistoryEventType"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static EpisodeHistoryEventType? FromStringOrDefault(string value)
        {
            if (value.Equals("unknown"))
                return EpisodeHistoryEventType.Unknown;

            if (value.Equals("grabbed"))
                return EpisodeHistoryEventType.Grabbed;

            if (value.Equals("seriesFolderImported"))
                return EpisodeHistoryEventType.SeriesFolderImported;

            if (value.Equals("downloadFolderImported"))
                return EpisodeHistoryEventType.DownloadFolderImported;

            if (value.Equals("downloadFailed"))
                return EpisodeHistoryEventType.DownloadFailed;

            if (value.Equals("episodeFileDeleted"))
                return EpisodeHistoryEventType.EpisodeFileDeleted;

            if (value.Equals("episodeFileRenamed"))
                return EpisodeHistoryEventType.EpisodeFileRenamed;

            if (value.Equals("downloadIgnored"))
                return EpisodeHistoryEventType.DownloadIgnored;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="EpisodeHistoryEventType"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ToJsonValue(EpisodeHistoryEventType value)
        {
            if (value == EpisodeHistoryEventType.Unknown)
                return "unknown";

            if (value == EpisodeHistoryEventType.Grabbed)
                return "grabbed";

            if (value == EpisodeHistoryEventType.SeriesFolderImported)
                return "seriesFolderImported";

            if (value == EpisodeHistoryEventType.DownloadFolderImported)
                return "downloadFolderImported";

            if (value == EpisodeHistoryEventType.DownloadFailed)
                return "downloadFailed";

            if (value == EpisodeHistoryEventType.EpisodeFileDeleted)
                return "episodeFileDeleted";

            if (value == EpisodeHistoryEventType.EpisodeFileRenamed)
                return "episodeFileRenamed";

            if (value == EpisodeHistoryEventType.DownloadIgnored)
                return "downloadIgnored";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="EpisodeHistoryEventType"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class EpisodeHistoryEventTypeJsonConverter : JsonConverter<EpisodeHistoryEventType>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override EpisodeHistoryEventType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            EpisodeHistoryEventType? result = rawValue == null
                ? null
                : EpisodeHistoryEventTypeValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the EpisodeHistoryEventType to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="episodeHistoryEventType"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, EpisodeHistoryEventType episodeHistoryEventType, JsonSerializerOptions options)
        {
            writer.WriteStringValue(EpisodeHistoryEventTypeValueConverter.ToJsonValue(episodeHistoryEventType).ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="EpisodeHistoryEventType"/>
    /// </summary>
    public class EpisodeHistoryEventTypeNullableJsonConverter : JsonConverter<EpisodeHistoryEventType?>
    {
        /// <summary>
        /// Returns a EpisodeHistoryEventType from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override EpisodeHistoryEventType? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            if (reader.TokenType == JsonTokenType.Null)
                return null;

            string? rawValue = reader.GetString();

            EpisodeHistoryEventType? result = rawValue == null
                ? null
                : EpisodeHistoryEventTypeValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the EpisodeHistoryEventType to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="episodeHistoryEventType"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, EpisodeHistoryEventType? episodeHistoryEventType, JsonSerializerOptions options)
        {
            if (episodeHistoryEventType.HasValue)
                writer.WriteStringValue(EpisodeHistoryEventTypeValueConverter.ToJsonValue(episodeHistoryEventType.Value).ToString());
            else
                writer.WriteNullValue();
        }
    }
}
