// <auto-generated>
/*
 * Whisparr
 *
 * Whisparr API docs - The v3 API docs apply to both v2 versions of Whisparr. Some functionality may only be available in v2 of the Whisparr application.
 *
 * The version of the OpenAPI document: 3.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Whisparr2.Net.Client;

namespace Whisparr2.Net.Model
{
    /// <summary>
    /// EpisodeFileListResource
    /// </summary>
    public partial class EpisodeFileListResource : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EpisodeFileListResource" /> class.
        /// </summary>
        /// <param name="episodeFileIds">episodeFileIds</param>
        /// <param name="languages">languages</param>
        /// <param name="quality">quality</param>
        /// <param name="sceneName">sceneName</param>
        /// <param name="releaseGroup">releaseGroup</param>
        [JsonConstructor]
        public EpisodeFileListResource(Option<List<int>?> episodeFileIds = default, Option<List<Language>?> languages = default, Option<QualityModel?> quality = default, Option<string?> sceneName = default, Option<string?> releaseGroup = default)
        {
            EpisodeFileIdsOption = episodeFileIds;
            LanguagesOption = languages;
            QualityOption = quality;
            SceneNameOption = sceneName;
            ReleaseGroupOption = releaseGroup;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of EpisodeFileIds
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<int>?> EpisodeFileIdsOption { get; private set; }

        /// <summary>
        /// Gets or Sets EpisodeFileIds
        /// </summary>
        [JsonPropertyName("episodeFileIds")]
        public List<int>? EpisodeFileIds { get { return this.EpisodeFileIdsOption.Value; } set { this.EpisodeFileIdsOption = new(value); } }

        /// <summary>
        /// Used to track the state of Languages
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<Language>?> LanguagesOption { get; private set; }

        /// <summary>
        /// Gets or Sets Languages
        /// </summary>
        [JsonPropertyName("languages")]
        public List<Language>? Languages { get { return this.LanguagesOption.Value; } set { this.LanguagesOption = new(value); } }

        /// <summary>
        /// Used to track the state of Quality
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<QualityModel?> QualityOption { get; private set; }

        /// <summary>
        /// Gets or Sets Quality
        /// </summary>
        [JsonPropertyName("quality")]
        public QualityModel? Quality { get { return this.QualityOption.Value; } set { this.QualityOption = new(value); } }

        /// <summary>
        /// Used to track the state of SceneName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SceneNameOption { get; private set; }

        /// <summary>
        /// Gets or Sets SceneName
        /// </summary>
        [JsonPropertyName("sceneName")]
        public string? SceneName { get { return this.SceneNameOption.Value; } set { this.SceneNameOption = new(value); } }

        /// <summary>
        /// Used to track the state of ReleaseGroup
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ReleaseGroupOption { get; private set; }

        /// <summary>
        /// Gets or Sets ReleaseGroup
        /// </summary>
        [JsonPropertyName("releaseGroup")]
        public string? ReleaseGroup { get { return this.ReleaseGroupOption.Value; } set { this.ReleaseGroupOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EpisodeFileListResource {\n");
            sb.Append("  EpisodeFileIds: ").Append(EpisodeFileIds).Append("\n");
            sb.Append("  Languages: ").Append(Languages).Append("\n");
            sb.Append("  Quality: ").Append(Quality).Append("\n");
            sb.Append("  SceneName: ").Append(SceneName).Append("\n");
            sb.Append("  ReleaseGroup: ").Append(ReleaseGroup).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="EpisodeFileListResource" />
    /// </summary>
    public partial class EpisodeFileListResourceJsonConverter : JsonConverter<EpisodeFileListResource>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="EpisodeFileListResourceJsonConverter" /> class.
        /// </summary>
        public EpisodeFileListResourceJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="EpisodeFileListResource" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override EpisodeFileListResource Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<int>?> episodeFileIds = default;
            Option<List<Language>?> languages = default;
            Option<QualityModel?> quality = default;
            Option<string?> sceneName = default;
            Option<string?> releaseGroup = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "episodeFileIds":
                            episodeFileIds = new Option<List<int>?>(JsonSerializer.Deserialize<List<int>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "languages":
                            languages = new Option<List<Language>?>(JsonSerializer.Deserialize<List<Language>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "quality":
                            quality = new Option<QualityModel?>(JsonSerializer.Deserialize<QualityModel>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "sceneName":
                            sceneName = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "releaseGroup":
                            releaseGroup = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (quality.IsSet && quality.Value == null)
                throw new ArgumentNullException(nameof(quality), "Property is not nullable for class EpisodeFileListResource.");

            return new EpisodeFileListResource(episodeFileIds, languages, quality, sceneName, releaseGroup);
        }

        /// <summary>
        /// Serializes a <see cref="EpisodeFileListResource" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="episodeFileListResource"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, EpisodeFileListResource episodeFileListResource, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, episodeFileListResource, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="EpisodeFileListResource" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="episodeFileListResource"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, EpisodeFileListResource episodeFileListResource, JsonSerializerOptions jsonSerializerOptions)
        {
            if (episodeFileListResource.QualityOption.IsSet && episodeFileListResource.Quality == null)
                throw new ArgumentNullException(nameof(episodeFileListResource.Quality), "Property is required for class EpisodeFileListResource.");

            if (episodeFileListResource.EpisodeFileIdsOption.IsSet)
                if (episodeFileListResource.EpisodeFileIdsOption.Value != null)
                {
                    writer.WritePropertyName("episodeFileIds");
                    JsonSerializer.Serialize(writer, episodeFileListResource.EpisodeFileIds, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("episodeFileIds");
            if (episodeFileListResource.LanguagesOption.IsSet)
                if (episodeFileListResource.LanguagesOption.Value != null)
                {
                    writer.WritePropertyName("languages");
                    JsonSerializer.Serialize(writer, episodeFileListResource.Languages, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("languages");
            if (episodeFileListResource.QualityOption.IsSet)
            {
                writer.WritePropertyName("quality");
                JsonSerializer.Serialize(writer, episodeFileListResource.Quality, jsonSerializerOptions);
            }
            if (episodeFileListResource.SceneNameOption.IsSet)
                if (episodeFileListResource.SceneNameOption.Value != null)
                    writer.WriteString("sceneName", episodeFileListResource.SceneName);
                else
                    writer.WriteNull("sceneName");

            if (episodeFileListResource.ReleaseGroupOption.IsSet)
                if (episodeFileListResource.ReleaseGroupOption.Value != null)
                    writer.WriteString("releaseGroup", episodeFileListResource.ReleaseGroup);
                else
                    writer.WriteNull("releaseGroup");
        }
    }
}
