// <auto-generated>
/*
 * Whisparr
 *
 * Whisparr API docs - The v3 API docs apply to both v2 versions of Whisparr. Some functionality may only be available in v2 of the Whisparr application.
 *
 * The version of the OpenAPI document: 3.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Whisparr2.Net.Client;

namespace Whisparr2.Net.Model
{
    /// <summary>
    /// HostConfigResource
    /// </summary>
    public partial class HostConfigResource : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HostConfigResource" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="bindAddress">bindAddress</param>
        /// <param name="port">port</param>
        /// <param name="sslPort">sslPort</param>
        /// <param name="enableSsl">enableSsl</param>
        /// <param name="launchBrowser">launchBrowser</param>
        /// <param name="authenticationMethod">authenticationMethod</param>
        /// <param name="authenticationRequired">authenticationRequired</param>
        /// <param name="analyticsEnabled">analyticsEnabled</param>
        /// <param name="username">username</param>
        /// <param name="password">password</param>
        /// <param name="logLevel">logLevel</param>
        /// <param name="logSizeLimit">logSizeLimit</param>
        /// <param name="consoleLogLevel">consoleLogLevel</param>
        /// <param name="branch">branch</param>
        /// <param name="apiKey">apiKey</param>
        /// <param name="sslCertPath">sslCertPath</param>
        /// <param name="sslCertPassword">sslCertPassword</param>
        /// <param name="urlBase">urlBase</param>
        /// <param name="instanceName">instanceName</param>
        /// <param name="applicationUrl">applicationUrl</param>
        /// <param name="updateAutomatically">updateAutomatically</param>
        /// <param name="updateMechanism">updateMechanism</param>
        /// <param name="updateScriptPath">updateScriptPath</param>
        /// <param name="proxyEnabled">proxyEnabled</param>
        /// <param name="proxyType">proxyType</param>
        /// <param name="proxyHostname">proxyHostname</param>
        /// <param name="proxyPort">proxyPort</param>
        /// <param name="proxyUsername">proxyUsername</param>
        /// <param name="proxyPassword">proxyPassword</param>
        /// <param name="proxyBypassFilter">proxyBypassFilter</param>
        /// <param name="proxyBypassLocalAddresses">proxyBypassLocalAddresses</param>
        /// <param name="certificateValidation">certificateValidation</param>
        /// <param name="backupFolder">backupFolder</param>
        /// <param name="backupInterval">backupInterval</param>
        /// <param name="backupRetention">backupRetention</param>
        [JsonConstructor]
        public HostConfigResource(Option<int?> id = default, Option<string?> bindAddress = default, Option<int?> port = default, Option<int?> sslPort = default, Option<bool?> enableSsl = default, Option<bool?> launchBrowser = default, Option<AuthenticationType?> authenticationMethod = default, Option<AuthenticationRequiredType?> authenticationRequired = default, Option<bool?> analyticsEnabled = default, Option<string?> username = default, Option<string?> password = default, Option<string?> logLevel = default, Option<int?> logSizeLimit = default, Option<string?> consoleLogLevel = default, Option<string?> branch = default, Option<string?> apiKey = default, Option<string?> sslCertPath = default, Option<string?> sslCertPassword = default, Option<string?> urlBase = default, Option<string?> instanceName = default, Option<string?> applicationUrl = default, Option<bool?> updateAutomatically = default, Option<UpdateMechanism?> updateMechanism = default, Option<string?> updateScriptPath = default, Option<bool?> proxyEnabled = default, Option<ProxyType?> proxyType = default, Option<string?> proxyHostname = default, Option<int?> proxyPort = default, Option<string?> proxyUsername = default, Option<string?> proxyPassword = default, Option<string?> proxyBypassFilter = default, Option<bool?> proxyBypassLocalAddresses = default, Option<CertificateValidationType?> certificateValidation = default, Option<string?> backupFolder = default, Option<int?> backupInterval = default, Option<int?> backupRetention = default)
        {
            IdOption = id;
            BindAddressOption = bindAddress;
            PortOption = port;
            SslPortOption = sslPort;
            EnableSslOption = enableSsl;
            LaunchBrowserOption = launchBrowser;
            AuthenticationMethodOption = authenticationMethod;
            AuthenticationRequiredOption = authenticationRequired;
            AnalyticsEnabledOption = analyticsEnabled;
            UsernameOption = username;
            PasswordOption = password;
            LogLevelOption = logLevel;
            LogSizeLimitOption = logSizeLimit;
            ConsoleLogLevelOption = consoleLogLevel;
            BranchOption = branch;
            ApiKeyOption = apiKey;
            SslCertPathOption = sslCertPath;
            SslCertPasswordOption = sslCertPassword;
            UrlBaseOption = urlBase;
            InstanceNameOption = instanceName;
            ApplicationUrlOption = applicationUrl;
            UpdateAutomaticallyOption = updateAutomatically;
            UpdateMechanismOption = updateMechanism;
            UpdateScriptPathOption = updateScriptPath;
            ProxyEnabledOption = proxyEnabled;
            ProxyTypeOption = proxyType;
            ProxyHostnameOption = proxyHostname;
            ProxyPortOption = proxyPort;
            ProxyUsernameOption = proxyUsername;
            ProxyPasswordOption = proxyPassword;
            ProxyBypassFilterOption = proxyBypassFilter;
            ProxyBypassLocalAddressesOption = proxyBypassLocalAddresses;
            CertificateValidationOption = certificateValidation;
            BackupFolderOption = backupFolder;
            BackupIntervalOption = backupInterval;
            BackupRetentionOption = backupRetention;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of AuthenticationMethod
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<AuthenticationType?> AuthenticationMethodOption { get; private set; }

        /// <summary>
        /// Gets or Sets AuthenticationMethod
        /// </summary>
        [JsonPropertyName("authenticationMethod")]
        public AuthenticationType? AuthenticationMethod { get { return this.AuthenticationMethodOption.Value; } set { this.AuthenticationMethodOption = new(value); } }

        /// <summary>
        /// Used to track the state of AuthenticationRequired
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<AuthenticationRequiredType?> AuthenticationRequiredOption { get; private set; }

        /// <summary>
        /// Gets or Sets AuthenticationRequired
        /// </summary>
        [JsonPropertyName("authenticationRequired")]
        public AuthenticationRequiredType? AuthenticationRequired { get { return this.AuthenticationRequiredOption.Value; } set { this.AuthenticationRequiredOption = new(value); } }

        /// <summary>
        /// Used to track the state of UpdateMechanism
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<UpdateMechanism?> UpdateMechanismOption { get; private set; }

        /// <summary>
        /// Gets or Sets UpdateMechanism
        /// </summary>
        [JsonPropertyName("updateMechanism")]
        public UpdateMechanism? UpdateMechanism { get { return this.UpdateMechanismOption.Value; } set { this.UpdateMechanismOption = new(value); } }

        /// <summary>
        /// Used to track the state of ProxyType
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<ProxyType?> ProxyTypeOption { get; private set; }

        /// <summary>
        /// Gets or Sets ProxyType
        /// </summary>
        [JsonPropertyName("proxyType")]
        public ProxyType? ProxyType { get { return this.ProxyTypeOption.Value; } set { this.ProxyTypeOption = new(value); } }

        /// <summary>
        /// Used to track the state of CertificateValidation
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<CertificateValidationType?> CertificateValidationOption { get; private set; }

        /// <summary>
        /// Gets or Sets CertificateValidation
        /// </summary>
        [JsonPropertyName("certificateValidation")]
        public CertificateValidationType? CertificateValidation { get { return this.CertificateValidationOption.Value; } set { this.CertificateValidationOption = new(value); } }

        /// <summary>
        /// Used to track the state of Id
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> IdOption { get; private set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public int? Id { get { return this.IdOption.Value; } set { this.IdOption = new(value); } }

        /// <summary>
        /// Used to track the state of BindAddress
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> BindAddressOption { get; private set; }

        /// <summary>
        /// Gets or Sets BindAddress
        /// </summary>
        [JsonPropertyName("bindAddress")]
        public string? BindAddress { get { return this.BindAddressOption.Value; } set { this.BindAddressOption = new(value); } }

        /// <summary>
        /// Used to track the state of Port
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> PortOption { get; private set; }

        /// <summary>
        /// Gets or Sets Port
        /// </summary>
        [JsonPropertyName("port")]
        public int? Port { get { return this.PortOption.Value; } set { this.PortOption = new(value); } }

        /// <summary>
        /// Used to track the state of SslPort
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> SslPortOption { get; private set; }

        /// <summary>
        /// Gets or Sets SslPort
        /// </summary>
        [JsonPropertyName("sslPort")]
        public int? SslPort { get { return this.SslPortOption.Value; } set { this.SslPortOption = new(value); } }

        /// <summary>
        /// Used to track the state of EnableSsl
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> EnableSslOption { get; private set; }

        /// <summary>
        /// Gets or Sets EnableSsl
        /// </summary>
        [JsonPropertyName("enableSsl")]
        public bool? EnableSsl { get { return this.EnableSslOption.Value; } set { this.EnableSslOption = new(value); } }

        /// <summary>
        /// Used to track the state of LaunchBrowser
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> LaunchBrowserOption { get; private set; }

        /// <summary>
        /// Gets or Sets LaunchBrowser
        /// </summary>
        [JsonPropertyName("launchBrowser")]
        public bool? LaunchBrowser { get { return this.LaunchBrowserOption.Value; } set { this.LaunchBrowserOption = new(value); } }

        /// <summary>
        /// Used to track the state of AnalyticsEnabled
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> AnalyticsEnabledOption { get; private set; }

        /// <summary>
        /// Gets or Sets AnalyticsEnabled
        /// </summary>
        [JsonPropertyName("analyticsEnabled")]
        public bool? AnalyticsEnabled { get { return this.AnalyticsEnabledOption.Value; } set { this.AnalyticsEnabledOption = new(value); } }

        /// <summary>
        /// Used to track the state of Username
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> UsernameOption { get; private set; }

        /// <summary>
        /// Gets or Sets Username
        /// </summary>
        [JsonPropertyName("username")]
        public string? Username { get { return this.UsernameOption.Value; } set { this.UsernameOption = new(value); } }

        /// <summary>
        /// Used to track the state of Password
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> PasswordOption { get; private set; }

        /// <summary>
        /// Gets or Sets Password
        /// </summary>
        [JsonPropertyName("password")]
        public string? Password { get { return this.PasswordOption.Value; } set { this.PasswordOption = new(value); } }

        /// <summary>
        /// Used to track the state of LogLevel
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> LogLevelOption { get; private set; }

        /// <summary>
        /// Gets or Sets LogLevel
        /// </summary>
        [JsonPropertyName("logLevel")]
        public string? LogLevel { get { return this.LogLevelOption.Value; } set { this.LogLevelOption = new(value); } }

        /// <summary>
        /// Used to track the state of LogSizeLimit
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> LogSizeLimitOption { get; private set; }

        /// <summary>
        /// Gets or Sets LogSizeLimit
        /// </summary>
        [JsonPropertyName("logSizeLimit")]
        public int? LogSizeLimit { get { return this.LogSizeLimitOption.Value; } set { this.LogSizeLimitOption = new(value); } }

        /// <summary>
        /// Used to track the state of ConsoleLogLevel
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ConsoleLogLevelOption { get; private set; }

        /// <summary>
        /// Gets or Sets ConsoleLogLevel
        /// </summary>
        [JsonPropertyName("consoleLogLevel")]
        public string? ConsoleLogLevel { get { return this.ConsoleLogLevelOption.Value; } set { this.ConsoleLogLevelOption = new(value); } }

        /// <summary>
        /// Used to track the state of Branch
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> BranchOption { get; private set; }

        /// <summary>
        /// Gets or Sets Branch
        /// </summary>
        [JsonPropertyName("branch")]
        public string? Branch { get { return this.BranchOption.Value; } set { this.BranchOption = new(value); } }

        /// <summary>
        /// Used to track the state of ApiKey
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ApiKeyOption { get; private set; }

        /// <summary>
        /// Gets or Sets ApiKey
        /// </summary>
        [JsonPropertyName("apiKey")]
        public string? ApiKey { get { return this.ApiKeyOption.Value; } set { this.ApiKeyOption = new(value); } }

        /// <summary>
        /// Used to track the state of SslCertPath
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SslCertPathOption { get; private set; }

        /// <summary>
        /// Gets or Sets SslCertPath
        /// </summary>
        [JsonPropertyName("sslCertPath")]
        public string? SslCertPath { get { return this.SslCertPathOption.Value; } set { this.SslCertPathOption = new(value); } }

        /// <summary>
        /// Used to track the state of SslCertPassword
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SslCertPasswordOption { get; private set; }

        /// <summary>
        /// Gets or Sets SslCertPassword
        /// </summary>
        [JsonPropertyName("sslCertPassword")]
        public string? SslCertPassword { get { return this.SslCertPasswordOption.Value; } set { this.SslCertPasswordOption = new(value); } }

        /// <summary>
        /// Used to track the state of UrlBase
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> UrlBaseOption { get; private set; }

        /// <summary>
        /// Gets or Sets UrlBase
        /// </summary>
        [JsonPropertyName("urlBase")]
        public string? UrlBase { get { return this.UrlBaseOption.Value; } set { this.UrlBaseOption = new(value); } }

        /// <summary>
        /// Used to track the state of InstanceName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> InstanceNameOption { get; private set; }

        /// <summary>
        /// Gets or Sets InstanceName
        /// </summary>
        [JsonPropertyName("instanceName")]
        public string? InstanceName { get { return this.InstanceNameOption.Value; } set { this.InstanceNameOption = new(value); } }

        /// <summary>
        /// Used to track the state of ApplicationUrl
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ApplicationUrlOption { get; private set; }

        /// <summary>
        /// Gets or Sets ApplicationUrl
        /// </summary>
        [JsonPropertyName("applicationUrl")]
        public string? ApplicationUrl { get { return this.ApplicationUrlOption.Value; } set { this.ApplicationUrlOption = new(value); } }

        /// <summary>
        /// Used to track the state of UpdateAutomatically
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> UpdateAutomaticallyOption { get; private set; }

        /// <summary>
        /// Gets or Sets UpdateAutomatically
        /// </summary>
        [JsonPropertyName("updateAutomatically")]
        public bool? UpdateAutomatically { get { return this.UpdateAutomaticallyOption.Value; } set { this.UpdateAutomaticallyOption = new(value); } }

        /// <summary>
        /// Used to track the state of UpdateScriptPath
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> UpdateScriptPathOption { get; private set; }

        /// <summary>
        /// Gets or Sets UpdateScriptPath
        /// </summary>
        [JsonPropertyName("updateScriptPath")]
        public string? UpdateScriptPath { get { return this.UpdateScriptPathOption.Value; } set { this.UpdateScriptPathOption = new(value); } }

        /// <summary>
        /// Used to track the state of ProxyEnabled
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> ProxyEnabledOption { get; private set; }

        /// <summary>
        /// Gets or Sets ProxyEnabled
        /// </summary>
        [JsonPropertyName("proxyEnabled")]
        public bool? ProxyEnabled { get { return this.ProxyEnabledOption.Value; } set { this.ProxyEnabledOption = new(value); } }

        /// <summary>
        /// Used to track the state of ProxyHostname
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ProxyHostnameOption { get; private set; }

        /// <summary>
        /// Gets or Sets ProxyHostname
        /// </summary>
        [JsonPropertyName("proxyHostname")]
        public string? ProxyHostname { get { return this.ProxyHostnameOption.Value; } set { this.ProxyHostnameOption = new(value); } }

        /// <summary>
        /// Used to track the state of ProxyPort
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> ProxyPortOption { get; private set; }

        /// <summary>
        /// Gets or Sets ProxyPort
        /// </summary>
        [JsonPropertyName("proxyPort")]
        public int? ProxyPort { get { return this.ProxyPortOption.Value; } set { this.ProxyPortOption = new(value); } }

        /// <summary>
        /// Used to track the state of ProxyUsername
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ProxyUsernameOption { get; private set; }

        /// <summary>
        /// Gets or Sets ProxyUsername
        /// </summary>
        [JsonPropertyName("proxyUsername")]
        public string? ProxyUsername { get { return this.ProxyUsernameOption.Value; } set { this.ProxyUsernameOption = new(value); } }

        /// <summary>
        /// Used to track the state of ProxyPassword
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ProxyPasswordOption { get; private set; }

        /// <summary>
        /// Gets or Sets ProxyPassword
        /// </summary>
        [JsonPropertyName("proxyPassword")]
        public string? ProxyPassword { get { return this.ProxyPasswordOption.Value; } set { this.ProxyPasswordOption = new(value); } }

        /// <summary>
        /// Used to track the state of ProxyBypassFilter
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ProxyBypassFilterOption { get; private set; }

        /// <summary>
        /// Gets or Sets ProxyBypassFilter
        /// </summary>
        [JsonPropertyName("proxyBypassFilter")]
        public string? ProxyBypassFilter { get { return this.ProxyBypassFilterOption.Value; } set { this.ProxyBypassFilterOption = new(value); } }

        /// <summary>
        /// Used to track the state of ProxyBypassLocalAddresses
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> ProxyBypassLocalAddressesOption { get; private set; }

        /// <summary>
        /// Gets or Sets ProxyBypassLocalAddresses
        /// </summary>
        [JsonPropertyName("proxyBypassLocalAddresses")]
        public bool? ProxyBypassLocalAddresses { get { return this.ProxyBypassLocalAddressesOption.Value; } set { this.ProxyBypassLocalAddressesOption = new(value); } }

        /// <summary>
        /// Used to track the state of BackupFolder
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> BackupFolderOption { get; private set; }

        /// <summary>
        /// Gets or Sets BackupFolder
        /// </summary>
        [JsonPropertyName("backupFolder")]
        public string? BackupFolder { get { return this.BackupFolderOption.Value; } set { this.BackupFolderOption = new(value); } }

        /// <summary>
        /// Used to track the state of BackupInterval
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> BackupIntervalOption { get; private set; }

        /// <summary>
        /// Gets or Sets BackupInterval
        /// </summary>
        [JsonPropertyName("backupInterval")]
        public int? BackupInterval { get { return this.BackupIntervalOption.Value; } set { this.BackupIntervalOption = new(value); } }

        /// <summary>
        /// Used to track the state of BackupRetention
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> BackupRetentionOption { get; private set; }

        /// <summary>
        /// Gets or Sets BackupRetention
        /// </summary>
        [JsonPropertyName("backupRetention")]
        public int? BackupRetention { get { return this.BackupRetentionOption.Value; } set { this.BackupRetentionOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class HostConfigResource {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  BindAddress: ").Append(BindAddress).Append("\n");
            sb.Append("  Port: ").Append(Port).Append("\n");
            sb.Append("  SslPort: ").Append(SslPort).Append("\n");
            sb.Append("  EnableSsl: ").Append(EnableSsl).Append("\n");
            sb.Append("  LaunchBrowser: ").Append(LaunchBrowser).Append("\n");
            sb.Append("  AuthenticationMethod: ").Append(AuthenticationMethod).Append("\n");
            sb.Append("  AuthenticationRequired: ").Append(AuthenticationRequired).Append("\n");
            sb.Append("  AnalyticsEnabled: ").Append(AnalyticsEnabled).Append("\n");
            sb.Append("  Username: ").Append(Username).Append("\n");
            sb.Append("  Password: ").Append(Password).Append("\n");
            sb.Append("  LogLevel: ").Append(LogLevel).Append("\n");
            sb.Append("  LogSizeLimit: ").Append(LogSizeLimit).Append("\n");
            sb.Append("  ConsoleLogLevel: ").Append(ConsoleLogLevel).Append("\n");
            sb.Append("  Branch: ").Append(Branch).Append("\n");
            sb.Append("  ApiKey: ").Append(ApiKey).Append("\n");
            sb.Append("  SslCertPath: ").Append(SslCertPath).Append("\n");
            sb.Append("  SslCertPassword: ").Append(SslCertPassword).Append("\n");
            sb.Append("  UrlBase: ").Append(UrlBase).Append("\n");
            sb.Append("  InstanceName: ").Append(InstanceName).Append("\n");
            sb.Append("  ApplicationUrl: ").Append(ApplicationUrl).Append("\n");
            sb.Append("  UpdateAutomatically: ").Append(UpdateAutomatically).Append("\n");
            sb.Append("  UpdateMechanism: ").Append(UpdateMechanism).Append("\n");
            sb.Append("  UpdateScriptPath: ").Append(UpdateScriptPath).Append("\n");
            sb.Append("  ProxyEnabled: ").Append(ProxyEnabled).Append("\n");
            sb.Append("  ProxyType: ").Append(ProxyType).Append("\n");
            sb.Append("  ProxyHostname: ").Append(ProxyHostname).Append("\n");
            sb.Append("  ProxyPort: ").Append(ProxyPort).Append("\n");
            sb.Append("  ProxyUsername: ").Append(ProxyUsername).Append("\n");
            sb.Append("  ProxyPassword: ").Append(ProxyPassword).Append("\n");
            sb.Append("  ProxyBypassFilter: ").Append(ProxyBypassFilter).Append("\n");
            sb.Append("  ProxyBypassLocalAddresses: ").Append(ProxyBypassLocalAddresses).Append("\n");
            sb.Append("  CertificateValidation: ").Append(CertificateValidation).Append("\n");
            sb.Append("  BackupFolder: ").Append(BackupFolder).Append("\n");
            sb.Append("  BackupInterval: ").Append(BackupInterval).Append("\n");
            sb.Append("  BackupRetention: ").Append(BackupRetention).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="HostConfigResource" />
    /// </summary>
    public partial class HostConfigResourceJsonConverter : JsonConverter<HostConfigResource>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="HostConfigResourceJsonConverter" /> class.
        /// </summary>
        public HostConfigResourceJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="HostConfigResource" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override HostConfigResource Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> id = default;
            Option<string?> bindAddress = default;
            Option<int?> port = default;
            Option<int?> sslPort = default;
            Option<bool?> enableSsl = default;
            Option<bool?> launchBrowser = default;
            Option<AuthenticationType?> authenticationMethod = default;
            Option<AuthenticationRequiredType?> authenticationRequired = default;
            Option<bool?> analyticsEnabled = default;
            Option<string?> username = default;
            Option<string?> password = default;
            Option<string?> logLevel = default;
            Option<int?> logSizeLimit = default;
            Option<string?> consoleLogLevel = default;
            Option<string?> branch = default;
            Option<string?> apiKey = default;
            Option<string?> sslCertPath = default;
            Option<string?> sslCertPassword = default;
            Option<string?> urlBase = default;
            Option<string?> instanceName = default;
            Option<string?> applicationUrl = default;
            Option<bool?> updateAutomatically = default;
            Option<UpdateMechanism?> updateMechanism = default;
            Option<string?> updateScriptPath = default;
            Option<bool?> proxyEnabled = default;
            Option<ProxyType?> proxyType = default;
            Option<string?> proxyHostname = default;
            Option<int?> proxyPort = default;
            Option<string?> proxyUsername = default;
            Option<string?> proxyPassword = default;
            Option<string?> proxyBypassFilter = default;
            Option<bool?> proxyBypassLocalAddresses = default;
            Option<CertificateValidationType?> certificateValidation = default;
            Option<string?> backupFolder = default;
            Option<int?> backupInterval = default;
            Option<int?> backupRetention = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "bindAddress":
                            bindAddress = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "port":
                            port = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "sslPort":
                            sslPort = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "enableSsl":
                            enableSsl = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "launchBrowser":
                            launchBrowser = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "authenticationMethod":
                            authenticationMethod = new Option<AuthenticationType?>(JsonSerializer.Deserialize<AuthenticationType?>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "authenticationRequired":
                            authenticationRequired = new Option<AuthenticationRequiredType?>(JsonSerializer.Deserialize<AuthenticationRequiredType?>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "analyticsEnabled":
                            analyticsEnabled = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "username":
                            username = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "password":
                            password = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "logLevel":
                            logLevel = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "logSizeLimit":
                            logSizeLimit = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "consoleLogLevel":
                            consoleLogLevel = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "branch":
                            branch = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "apiKey":
                            apiKey = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "sslCertPath":
                            sslCertPath = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "sslCertPassword":
                            sslCertPassword = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "urlBase":
                            urlBase = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "instanceName":
                            instanceName = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "applicationUrl":
                            applicationUrl = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "updateAutomatically":
                            updateAutomatically = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "updateMechanism":
                            updateMechanism = new Option<UpdateMechanism?>(JsonSerializer.Deserialize<UpdateMechanism?>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "updateScriptPath":
                            updateScriptPath = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "proxyEnabled":
                            proxyEnabled = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "proxyType":
                            proxyType = new Option<ProxyType?>(JsonSerializer.Deserialize<ProxyType?>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "proxyHostname":
                            proxyHostname = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "proxyPort":
                            proxyPort = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "proxyUsername":
                            proxyUsername = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "proxyPassword":
                            proxyPassword = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "proxyBypassFilter":
                            proxyBypassFilter = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "proxyBypassLocalAddresses":
                            proxyBypassLocalAddresses = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "certificateValidation":
                            certificateValidation = new Option<CertificateValidationType?>(JsonSerializer.Deserialize<CertificateValidationType?>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "backupFolder":
                            backupFolder = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "backupInterval":
                            backupInterval = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "backupRetention":
                            backupRetention = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class HostConfigResource.");

            if (port.IsSet && port.Value == null)
                throw new ArgumentNullException(nameof(port), "Property is not nullable for class HostConfigResource.");

            if (sslPort.IsSet && sslPort.Value == null)
                throw new ArgumentNullException(nameof(sslPort), "Property is not nullable for class HostConfigResource.");

            if (enableSsl.IsSet && enableSsl.Value == null)
                throw new ArgumentNullException(nameof(enableSsl), "Property is not nullable for class HostConfigResource.");

            if (launchBrowser.IsSet && launchBrowser.Value == null)
                throw new ArgumentNullException(nameof(launchBrowser), "Property is not nullable for class HostConfigResource.");

            if (authenticationMethod.IsSet && authenticationMethod.Value == null)
                throw new ArgumentNullException(nameof(authenticationMethod), "Property is not nullable for class HostConfigResource.");

            if (authenticationRequired.IsSet && authenticationRequired.Value == null)
                throw new ArgumentNullException(nameof(authenticationRequired), "Property is not nullable for class HostConfigResource.");

            if (analyticsEnabled.IsSet && analyticsEnabled.Value == null)
                throw new ArgumentNullException(nameof(analyticsEnabled), "Property is not nullable for class HostConfigResource.");

            if (updateAutomatically.IsSet && updateAutomatically.Value == null)
                throw new ArgumentNullException(nameof(updateAutomatically), "Property is not nullable for class HostConfigResource.");

            if (updateMechanism.IsSet && updateMechanism.Value == null)
                throw new ArgumentNullException(nameof(updateMechanism), "Property is not nullable for class HostConfigResource.");

            if (proxyEnabled.IsSet && proxyEnabled.Value == null)
                throw new ArgumentNullException(nameof(proxyEnabled), "Property is not nullable for class HostConfigResource.");

            if (proxyType.IsSet && proxyType.Value == null)
                throw new ArgumentNullException(nameof(proxyType), "Property is not nullable for class HostConfigResource.");

            if (proxyPort.IsSet && proxyPort.Value == null)
                throw new ArgumentNullException(nameof(proxyPort), "Property is not nullable for class HostConfigResource.");

            if (proxyBypassLocalAddresses.IsSet && proxyBypassLocalAddresses.Value == null)
                throw new ArgumentNullException(nameof(proxyBypassLocalAddresses), "Property is not nullable for class HostConfigResource.");

            if (certificateValidation.IsSet && certificateValidation.Value == null)
                throw new ArgumentNullException(nameof(certificateValidation), "Property is not nullable for class HostConfigResource.");

            if (backupInterval.IsSet && backupInterval.Value == null)
                throw new ArgumentNullException(nameof(backupInterval), "Property is not nullable for class HostConfigResource.");

            if (backupRetention.IsSet && backupRetention.Value == null)
                throw new ArgumentNullException(nameof(backupRetention), "Property is not nullable for class HostConfigResource.");

            return new HostConfigResource(id, bindAddress, port, sslPort, enableSsl, launchBrowser, authenticationMethod, authenticationRequired, analyticsEnabled, username, password, logLevel, logSizeLimit, consoleLogLevel, branch, apiKey, sslCertPath, sslCertPassword, urlBase, instanceName, applicationUrl, updateAutomatically, updateMechanism, updateScriptPath, proxyEnabled, proxyType, proxyHostname, proxyPort, proxyUsername, proxyPassword, proxyBypassFilter, proxyBypassLocalAddresses, certificateValidation, backupFolder, backupInterval, backupRetention);
        }

        /// <summary>
        /// Serializes a <see cref="HostConfigResource" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="hostConfigResource"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, HostConfigResource hostConfigResource, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, hostConfigResource, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="HostConfigResource" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="hostConfigResource"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, HostConfigResource hostConfigResource, JsonSerializerOptions jsonSerializerOptions)
        {
            if (hostConfigResource.IdOption.IsSet)
                writer.WriteNumber("id", hostConfigResource.IdOption.Value!.Value);

            if (hostConfigResource.BindAddressOption.IsSet)
                if (hostConfigResource.BindAddressOption.Value != null)
                    writer.WriteString("bindAddress", hostConfigResource.BindAddress);
                else
                    writer.WriteNull("bindAddress");

            if (hostConfigResource.PortOption.IsSet)
                writer.WriteNumber("port", hostConfigResource.PortOption.Value!.Value);

            if (hostConfigResource.SslPortOption.IsSet)
                writer.WriteNumber("sslPort", hostConfigResource.SslPortOption.Value!.Value);

            if (hostConfigResource.EnableSslOption.IsSet)
                writer.WriteBoolean("enableSsl", hostConfigResource.EnableSslOption.Value!.Value);

            if (hostConfigResource.LaunchBrowserOption.IsSet)
                writer.WriteBoolean("launchBrowser", hostConfigResource.LaunchBrowserOption.Value!.Value);

            if (hostConfigResource.AuthenticationMethodOption.IsSet)
            {
                var authenticationMethodRawValue = AuthenticationTypeValueConverter.ToJsonValue(hostConfigResource.AuthenticationMethod!.Value);
                writer.WriteString("authenticationMethod", authenticationMethodRawValue);
            }
            if (hostConfigResource.AuthenticationRequiredOption.IsSet)
            {
                var authenticationRequiredRawValue = AuthenticationRequiredTypeValueConverter.ToJsonValue(hostConfigResource.AuthenticationRequired!.Value);
                writer.WriteString("authenticationRequired", authenticationRequiredRawValue);
            }
            if (hostConfigResource.AnalyticsEnabledOption.IsSet)
                writer.WriteBoolean("analyticsEnabled", hostConfigResource.AnalyticsEnabledOption.Value!.Value);

            if (hostConfigResource.UsernameOption.IsSet)
                if (hostConfigResource.UsernameOption.Value != null)
                    writer.WriteString("username", hostConfigResource.Username);
                else
                    writer.WriteNull("username");

            if (hostConfigResource.PasswordOption.IsSet)
                if (hostConfigResource.PasswordOption.Value != null)
                    writer.WriteString("password", hostConfigResource.Password);
                else
                    writer.WriteNull("password");

            if (hostConfigResource.LogLevelOption.IsSet)
                if (hostConfigResource.LogLevelOption.Value != null)
                    writer.WriteString("logLevel", hostConfigResource.LogLevel);
                else
                    writer.WriteNull("logLevel");

            if (hostConfigResource.LogSizeLimitOption.IsSet)
                if (hostConfigResource.LogSizeLimitOption.Value != null)
                    writer.WriteNumber("logSizeLimit", hostConfigResource.LogSizeLimitOption.Value!.Value);
                else
                    writer.WriteNull("logSizeLimit");

            if (hostConfigResource.ConsoleLogLevelOption.IsSet)
                if (hostConfigResource.ConsoleLogLevelOption.Value != null)
                    writer.WriteString("consoleLogLevel", hostConfigResource.ConsoleLogLevel);
                else
                    writer.WriteNull("consoleLogLevel");

            if (hostConfigResource.BranchOption.IsSet)
                if (hostConfigResource.BranchOption.Value != null)
                    writer.WriteString("branch", hostConfigResource.Branch);
                else
                    writer.WriteNull("branch");

            if (hostConfigResource.ApiKeyOption.IsSet)
                if (hostConfigResource.ApiKeyOption.Value != null)
                    writer.WriteString("apiKey", hostConfigResource.ApiKey);
                else
                    writer.WriteNull("apiKey");

            if (hostConfigResource.SslCertPathOption.IsSet)
                if (hostConfigResource.SslCertPathOption.Value != null)
                    writer.WriteString("sslCertPath", hostConfigResource.SslCertPath);
                else
                    writer.WriteNull("sslCertPath");

            if (hostConfigResource.SslCertPasswordOption.IsSet)
                if (hostConfigResource.SslCertPasswordOption.Value != null)
                    writer.WriteString("sslCertPassword", hostConfigResource.SslCertPassword);
                else
                    writer.WriteNull("sslCertPassword");

            if (hostConfigResource.UrlBaseOption.IsSet)
                if (hostConfigResource.UrlBaseOption.Value != null)
                    writer.WriteString("urlBase", hostConfigResource.UrlBase);
                else
                    writer.WriteNull("urlBase");

            if (hostConfigResource.InstanceNameOption.IsSet)
                if (hostConfigResource.InstanceNameOption.Value != null)
                    writer.WriteString("instanceName", hostConfigResource.InstanceName);
                else
                    writer.WriteNull("instanceName");

            if (hostConfigResource.ApplicationUrlOption.IsSet)
                if (hostConfigResource.ApplicationUrlOption.Value != null)
                    writer.WriteString("applicationUrl", hostConfigResource.ApplicationUrl);
                else
                    writer.WriteNull("applicationUrl");

            if (hostConfigResource.UpdateAutomaticallyOption.IsSet)
                writer.WriteBoolean("updateAutomatically", hostConfigResource.UpdateAutomaticallyOption.Value!.Value);

            if (hostConfigResource.UpdateMechanismOption.IsSet)
            {
                var updateMechanismRawValue = UpdateMechanismValueConverter.ToJsonValue(hostConfigResource.UpdateMechanism!.Value);
                writer.WriteString("updateMechanism", updateMechanismRawValue);
            }
            if (hostConfigResource.UpdateScriptPathOption.IsSet)
                if (hostConfigResource.UpdateScriptPathOption.Value != null)
                    writer.WriteString("updateScriptPath", hostConfigResource.UpdateScriptPath);
                else
                    writer.WriteNull("updateScriptPath");

            if (hostConfigResource.ProxyEnabledOption.IsSet)
                writer.WriteBoolean("proxyEnabled", hostConfigResource.ProxyEnabledOption.Value!.Value);

            if (hostConfigResource.ProxyTypeOption.IsSet)
            {
                var proxyTypeRawValue = ProxyTypeValueConverter.ToJsonValue(hostConfigResource.ProxyType!.Value);
                writer.WriteString("proxyType", proxyTypeRawValue);
            }
            if (hostConfigResource.ProxyHostnameOption.IsSet)
                if (hostConfigResource.ProxyHostnameOption.Value != null)
                    writer.WriteString("proxyHostname", hostConfigResource.ProxyHostname);
                else
                    writer.WriteNull("proxyHostname");

            if (hostConfigResource.ProxyPortOption.IsSet)
                writer.WriteNumber("proxyPort", hostConfigResource.ProxyPortOption.Value!.Value);

            if (hostConfigResource.ProxyUsernameOption.IsSet)
                if (hostConfigResource.ProxyUsernameOption.Value != null)
                    writer.WriteString("proxyUsername", hostConfigResource.ProxyUsername);
                else
                    writer.WriteNull("proxyUsername");

            if (hostConfigResource.ProxyPasswordOption.IsSet)
                if (hostConfigResource.ProxyPasswordOption.Value != null)
                    writer.WriteString("proxyPassword", hostConfigResource.ProxyPassword);
                else
                    writer.WriteNull("proxyPassword");

            if (hostConfigResource.ProxyBypassFilterOption.IsSet)
                if (hostConfigResource.ProxyBypassFilterOption.Value != null)
                    writer.WriteString("proxyBypassFilter", hostConfigResource.ProxyBypassFilter);
                else
                    writer.WriteNull("proxyBypassFilter");

            if (hostConfigResource.ProxyBypassLocalAddressesOption.IsSet)
                writer.WriteBoolean("proxyBypassLocalAddresses", hostConfigResource.ProxyBypassLocalAddressesOption.Value!.Value);

            if (hostConfigResource.CertificateValidationOption.IsSet)
            {
                var certificateValidationRawValue = CertificateValidationTypeValueConverter.ToJsonValue(hostConfigResource.CertificateValidation!.Value);
                writer.WriteString("certificateValidation", certificateValidationRawValue);
            }
            if (hostConfigResource.BackupFolderOption.IsSet)
                if (hostConfigResource.BackupFolderOption.Value != null)
                    writer.WriteString("backupFolder", hostConfigResource.BackupFolder);
                else
                    writer.WriteNull("backupFolder");

            if (hostConfigResource.BackupIntervalOption.IsSet)
                writer.WriteNumber("backupInterval", hostConfigResource.BackupIntervalOption.Value!.Value);

            if (hostConfigResource.BackupRetentionOption.IsSet)
                writer.WriteNumber("backupRetention", hostConfigResource.BackupRetentionOption.Value!.Value);
        }
    }
}
