// <auto-generated>
/*
 * Whisparr
 *
 * Whisparr API docs - The v3 API docs apply to both v2 versions of Whisparr. Some functionality may only be available in v2 of the Whisparr application.
 *
 * The version of the OpenAPI document: 3.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Whisparr2.Net.Client;

namespace Whisparr2.Net.Model
{
    /// <summary>
    /// IndexerConfigResource
    /// </summary>
    public partial class IndexerConfigResource : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="IndexerConfigResource" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="minimumAge">minimumAge</param>
        /// <param name="retention">retention</param>
        /// <param name="maximumSize">maximumSize</param>
        /// <param name="rssSyncInterval">rssSyncInterval</param>
        [JsonConstructor]
        public IndexerConfigResource(Option<int?> id = default, Option<int?> minimumAge = default, Option<int?> retention = default, Option<int?> maximumSize = default, Option<int?> rssSyncInterval = default)
        {
            IdOption = id;
            MinimumAgeOption = minimumAge;
            RetentionOption = retention;
            MaximumSizeOption = maximumSize;
            RssSyncIntervalOption = rssSyncInterval;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Id
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> IdOption { get; private set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public int? Id { get { return this.IdOption.Value; } set { this.IdOption = new(value); } }

        /// <summary>
        /// Used to track the state of MinimumAge
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> MinimumAgeOption { get; private set; }

        /// <summary>
        /// Gets or Sets MinimumAge
        /// </summary>
        [JsonPropertyName("minimumAge")]
        public int? MinimumAge { get { return this.MinimumAgeOption.Value; } set { this.MinimumAgeOption = new(value); } }

        /// <summary>
        /// Used to track the state of Retention
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> RetentionOption { get; private set; }

        /// <summary>
        /// Gets or Sets Retention
        /// </summary>
        [JsonPropertyName("retention")]
        public int? Retention { get { return this.RetentionOption.Value; } set { this.RetentionOption = new(value); } }

        /// <summary>
        /// Used to track the state of MaximumSize
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> MaximumSizeOption { get; private set; }

        /// <summary>
        /// Gets or Sets MaximumSize
        /// </summary>
        [JsonPropertyName("maximumSize")]
        public int? MaximumSize { get { return this.MaximumSizeOption.Value; } set { this.MaximumSizeOption = new(value); } }

        /// <summary>
        /// Used to track the state of RssSyncInterval
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> RssSyncIntervalOption { get; private set; }

        /// <summary>
        /// Gets or Sets RssSyncInterval
        /// </summary>
        [JsonPropertyName("rssSyncInterval")]
        public int? RssSyncInterval { get { return this.RssSyncIntervalOption.Value; } set { this.RssSyncIntervalOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class IndexerConfigResource {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  MinimumAge: ").Append(MinimumAge).Append("\n");
            sb.Append("  Retention: ").Append(Retention).Append("\n");
            sb.Append("  MaximumSize: ").Append(MaximumSize).Append("\n");
            sb.Append("  RssSyncInterval: ").Append(RssSyncInterval).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="IndexerConfigResource" />
    /// </summary>
    public partial class IndexerConfigResourceJsonConverter : JsonConverter<IndexerConfigResource>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="IndexerConfigResourceJsonConverter" /> class.
        /// </summary>
        public IndexerConfigResourceJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="IndexerConfigResource" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override IndexerConfigResource Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> id = default;
            Option<int?> minimumAge = default;
            Option<int?> retention = default;
            Option<int?> maximumSize = default;
            Option<int?> rssSyncInterval = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "minimumAge":
                            minimumAge = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "retention":
                            retention = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "maximumSize":
                            maximumSize = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "rssSyncInterval":
                            rssSyncInterval = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class IndexerConfigResource.");

            if (minimumAge.IsSet && minimumAge.Value == null)
                throw new ArgumentNullException(nameof(minimumAge), "Property is not nullable for class IndexerConfigResource.");

            if (retention.IsSet && retention.Value == null)
                throw new ArgumentNullException(nameof(retention), "Property is not nullable for class IndexerConfigResource.");

            if (maximumSize.IsSet && maximumSize.Value == null)
                throw new ArgumentNullException(nameof(maximumSize), "Property is not nullable for class IndexerConfigResource.");

            if (rssSyncInterval.IsSet && rssSyncInterval.Value == null)
                throw new ArgumentNullException(nameof(rssSyncInterval), "Property is not nullable for class IndexerConfigResource.");

            return new IndexerConfigResource(id, minimumAge, retention, maximumSize, rssSyncInterval);
        }

        /// <summary>
        /// Serializes a <see cref="IndexerConfigResource" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="indexerConfigResource"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, IndexerConfigResource indexerConfigResource, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, indexerConfigResource, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="IndexerConfigResource" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="indexerConfigResource"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, IndexerConfigResource indexerConfigResource, JsonSerializerOptions jsonSerializerOptions)
        {
            if (indexerConfigResource.IdOption.IsSet)
                writer.WriteNumber("id", indexerConfigResource.IdOption.Value!.Value);

            if (indexerConfigResource.MinimumAgeOption.IsSet)
                writer.WriteNumber("minimumAge", indexerConfigResource.MinimumAgeOption.Value!.Value);

            if (indexerConfigResource.RetentionOption.IsSet)
                writer.WriteNumber("retention", indexerConfigResource.RetentionOption.Value!.Value);

            if (indexerConfigResource.MaximumSizeOption.IsSet)
                writer.WriteNumber("maximumSize", indexerConfigResource.MaximumSizeOption.Value!.Value);

            if (indexerConfigResource.RssSyncIntervalOption.IsSet)
                writer.WriteNumber("rssSyncInterval", indexerConfigResource.RssSyncIntervalOption.Value!.Value);
        }
    }
}
