// <auto-generated>
/*
 * Whisparr
 *
 * Whisparr API docs - The v3 API docs apply to both v2 versions of Whisparr. Some functionality may only be available in v2 of the Whisparr application.
 *
 * The version of the OpenAPI document: 3.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Whisparr2.Net.Client;

namespace Whisparr2.Net.Model
{
    /// <summary>
    /// LanguageProfileResource
    /// </summary>
    public partial class LanguageProfileResource : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LanguageProfileResource" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="name">name</param>
        /// <param name="upgradeAllowed">upgradeAllowed</param>
        /// <param name="cutoff">cutoff</param>
        /// <param name="languages">languages</param>
        [JsonConstructor]
        public LanguageProfileResource(Option<int?> id = default, Option<string?> name = default, Option<bool?> upgradeAllowed = default, Option<Language?> cutoff = default, Option<List<LanguageProfileItemResource>?> languages = default)
        {
            IdOption = id;
            NameOption = name;
            UpgradeAllowedOption = upgradeAllowed;
            CutoffOption = cutoff;
            LanguagesOption = languages;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Id
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> IdOption { get; private set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public int? Id { get { return this.IdOption.Value; } set { this.IdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Name
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NameOption { get; private set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [JsonPropertyName("name")]
        public string? Name { get { return this.NameOption.Value; } set { this.NameOption = new(value); } }

        /// <summary>
        /// Used to track the state of UpgradeAllowed
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> UpgradeAllowedOption { get; private set; }

        /// <summary>
        /// Gets or Sets UpgradeAllowed
        /// </summary>
        [JsonPropertyName("upgradeAllowed")]
        public bool? UpgradeAllowed { get { return this.UpgradeAllowedOption.Value; } set { this.UpgradeAllowedOption = new(value); } }

        /// <summary>
        /// Used to track the state of Cutoff
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Language?> CutoffOption { get; private set; }

        /// <summary>
        /// Gets or Sets Cutoff
        /// </summary>
        [JsonPropertyName("cutoff")]
        public Language? Cutoff { get { return this.CutoffOption.Value; } set { this.CutoffOption = new(value); } }

        /// <summary>
        /// Used to track the state of Languages
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<LanguageProfileItemResource>?> LanguagesOption { get; private set; }

        /// <summary>
        /// Gets or Sets Languages
        /// </summary>
        [JsonPropertyName("languages")]
        public List<LanguageProfileItemResource>? Languages { get { return this.LanguagesOption.Value; } set { this.LanguagesOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class LanguageProfileResource {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  UpgradeAllowed: ").Append(UpgradeAllowed).Append("\n");
            sb.Append("  Cutoff: ").Append(Cutoff).Append("\n");
            sb.Append("  Languages: ").Append(Languages).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="LanguageProfileResource" />
    /// </summary>
    public partial class LanguageProfileResourceJsonConverter : JsonConverter<LanguageProfileResource>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="LanguageProfileResourceJsonConverter" /> class.
        /// </summary>
        public LanguageProfileResourceJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="LanguageProfileResource" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override LanguageProfileResource Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> id = default;
            Option<string?> name = default;
            Option<bool?> upgradeAllowed = default;
            Option<Language?> cutoff = default;
            Option<List<LanguageProfileItemResource>?> languages = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "upgradeAllowed":
                            upgradeAllowed = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "cutoff":
                            cutoff = new Option<Language?>(JsonSerializer.Deserialize<Language>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "languages":
                            languages = new Option<List<LanguageProfileItemResource>?>(JsonSerializer.Deserialize<List<LanguageProfileItemResource>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class LanguageProfileResource.");

            if (upgradeAllowed.IsSet && upgradeAllowed.Value == null)
                throw new ArgumentNullException(nameof(upgradeAllowed), "Property is not nullable for class LanguageProfileResource.");

            if (cutoff.IsSet && cutoff.Value == null)
                throw new ArgumentNullException(nameof(cutoff), "Property is not nullable for class LanguageProfileResource.");

            return new LanguageProfileResource(id, name, upgradeAllowed, cutoff, languages);
        }

        /// <summary>
        /// Serializes a <see cref="LanguageProfileResource" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="languageProfileResource"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, LanguageProfileResource languageProfileResource, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, languageProfileResource, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="LanguageProfileResource" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="languageProfileResource"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, LanguageProfileResource languageProfileResource, JsonSerializerOptions jsonSerializerOptions)
        {
            if (languageProfileResource.CutoffOption.IsSet && languageProfileResource.Cutoff == null)
                throw new ArgumentNullException(nameof(languageProfileResource.Cutoff), "Property is required for class LanguageProfileResource.");

            if (languageProfileResource.IdOption.IsSet)
                writer.WriteNumber("id", languageProfileResource.IdOption.Value!.Value);

            if (languageProfileResource.NameOption.IsSet)
                if (languageProfileResource.NameOption.Value != null)
                    writer.WriteString("name", languageProfileResource.Name);
                else
                    writer.WriteNull("name");

            if (languageProfileResource.UpgradeAllowedOption.IsSet)
                writer.WriteBoolean("upgradeAllowed", languageProfileResource.UpgradeAllowedOption.Value!.Value);

            if (languageProfileResource.CutoffOption.IsSet)
            {
                writer.WritePropertyName("cutoff");
                JsonSerializer.Serialize(writer, languageProfileResource.Cutoff, jsonSerializerOptions);
            }
            if (languageProfileResource.LanguagesOption.IsSet)
                if (languageProfileResource.LanguagesOption.Value != null)
                {
                    writer.WritePropertyName("languages");
                    JsonSerializer.Serialize(writer, languageProfileResource.Languages, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("languages");
        }
    }
}
