// <auto-generated>
/*
 * Whisparr
 *
 * Whisparr API docs - The v3 API docs apply to both v2 versions of Whisparr. Some functionality may only be available in v2 of the Whisparr application.
 *
 * The version of the OpenAPI document: 3.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Whisparr2.Net.Client;

namespace Whisparr2.Net.Model
{
    /// <summary>
    /// LanguageProfileItemResource
    /// </summary>
    public partial class LanguageProfileItemResource : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LanguageProfileItemResource" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="language">language</param>
        /// <param name="allowed">allowed</param>
        [JsonConstructor]
        public LanguageProfileItemResource(Option<int?> id = default, Option<Language?> language = default, Option<bool?> allowed = default)
        {
            IdOption = id;
            LanguageOption = language;
            AllowedOption = allowed;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Id
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> IdOption { get; private set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public int? Id { get { return this.IdOption.Value; } set { this.IdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Language
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Language?> LanguageOption { get; private set; }

        /// <summary>
        /// Gets or Sets Language
        /// </summary>
        [JsonPropertyName("language")]
        public Language? Language { get { return this.LanguageOption.Value; } set { this.LanguageOption = new(value); } }

        /// <summary>
        /// Used to track the state of Allowed
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> AllowedOption { get; private set; }

        /// <summary>
        /// Gets or Sets Allowed
        /// </summary>
        [JsonPropertyName("allowed")]
        public bool? Allowed { get { return this.AllowedOption.Value; } set { this.AllowedOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class LanguageProfileItemResource {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Language: ").Append(Language).Append("\n");
            sb.Append("  Allowed: ").Append(Allowed).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="LanguageProfileItemResource" />
    /// </summary>
    public partial class LanguageProfileItemResourceJsonConverter : JsonConverter<LanguageProfileItemResource>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="LanguageProfileItemResourceJsonConverter" /> class.
        /// </summary>
        public LanguageProfileItemResourceJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="LanguageProfileItemResource" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override LanguageProfileItemResource Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> id = default;
            Option<Language?> language = default;
            Option<bool?> allowed = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "language":
                            language = new Option<Language?>(JsonSerializer.Deserialize<Language>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "allowed":
                            allowed = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class LanguageProfileItemResource.");

            if (language.IsSet && language.Value == null)
                throw new ArgumentNullException(nameof(language), "Property is not nullable for class LanguageProfileItemResource.");

            if (allowed.IsSet && allowed.Value == null)
                throw new ArgumentNullException(nameof(allowed), "Property is not nullable for class LanguageProfileItemResource.");

            return new LanguageProfileItemResource(id, language, allowed);
        }

        /// <summary>
        /// Serializes a <see cref="LanguageProfileItemResource" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="languageProfileItemResource"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, LanguageProfileItemResource languageProfileItemResource, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, languageProfileItemResource, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="LanguageProfileItemResource" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="languageProfileItemResource"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, LanguageProfileItemResource languageProfileItemResource, JsonSerializerOptions jsonSerializerOptions)
        {
            if (languageProfileItemResource.LanguageOption.IsSet && languageProfileItemResource.Language == null)
                throw new ArgumentNullException(nameof(languageProfileItemResource.Language), "Property is required for class LanguageProfileItemResource.");

            if (languageProfileItemResource.IdOption.IsSet)
                writer.WriteNumber("id", languageProfileItemResource.IdOption.Value!.Value);

            if (languageProfileItemResource.LanguageOption.IsSet)
            {
                writer.WritePropertyName("language");
                JsonSerializer.Serialize(writer, languageProfileItemResource.Language, jsonSerializerOptions);
            }
            if (languageProfileItemResource.AllowedOption.IsSet)
                writer.WriteBoolean("allowed", languageProfileItemResource.AllowedOption.Value!.Value);
        }
    }
}
