// <auto-generated>
/*
 * Whisparr
 *
 * Whisparr API docs - The v3 API docs apply to both v2 versions of Whisparr. Some functionality may only be available in v2 of the Whisparr application.
 *
 * The version of the OpenAPI document: 3.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Whisparr2.Net.Client;

namespace Whisparr2.Net.Model
{
    /// <summary>
    /// Defines ListSyncLevelType
    /// </summary>
    public enum ListSyncLevelType
    {
        /// <summary>
        /// Enum Disabled for value: disabled
        /// </summary>
        Disabled = 1,

        /// <summary>
        /// Enum LogOnly for value: logOnly
        /// </summary>
        LogOnly = 2,

        /// <summary>
        /// Enum KeepAndUnmonitor for value: keepAndUnmonitor
        /// </summary>
        KeepAndUnmonitor = 3,

        /// <summary>
        /// Enum KeepAndTag for value: keepAndTag
        /// </summary>
        KeepAndTag = 4
    }

    /// <summary>
    /// Converts <see cref="ListSyncLevelType"/> to and from the JSON value
    /// </summary>
    public static class ListSyncLevelTypeValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="ListSyncLevelType"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static ListSyncLevelType FromString(string value)
        {
            if (value.Equals("disabled"))
                return ListSyncLevelType.Disabled;

            if (value.Equals("logOnly"))
                return ListSyncLevelType.LogOnly;

            if (value.Equals("keepAndUnmonitor"))
                return ListSyncLevelType.KeepAndUnmonitor;

            if (value.Equals("keepAndTag"))
                return ListSyncLevelType.KeepAndTag;

            throw new NotImplementedException($"Could not convert value to type ListSyncLevelType: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="ListSyncLevelType"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static ListSyncLevelType? FromStringOrDefault(string value)
        {
            if (value.Equals("disabled"))
                return ListSyncLevelType.Disabled;

            if (value.Equals("logOnly"))
                return ListSyncLevelType.LogOnly;

            if (value.Equals("keepAndUnmonitor"))
                return ListSyncLevelType.KeepAndUnmonitor;

            if (value.Equals("keepAndTag"))
                return ListSyncLevelType.KeepAndTag;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="ListSyncLevelType"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ToJsonValue(ListSyncLevelType value)
        {
            if (value == ListSyncLevelType.Disabled)
                return "disabled";

            if (value == ListSyncLevelType.LogOnly)
                return "logOnly";

            if (value == ListSyncLevelType.KeepAndUnmonitor)
                return "keepAndUnmonitor";

            if (value == ListSyncLevelType.KeepAndTag)
                return "keepAndTag";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ListSyncLevelType"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class ListSyncLevelTypeJsonConverter : JsonConverter<ListSyncLevelType>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override ListSyncLevelType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            ListSyncLevelType? result = rawValue == null
                ? null
                : ListSyncLevelTypeValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the ListSyncLevelType to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="listSyncLevelType"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, ListSyncLevelType listSyncLevelType, JsonSerializerOptions options)
        {
            writer.WriteStringValue(ListSyncLevelTypeValueConverter.ToJsonValue(listSyncLevelType).ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ListSyncLevelType"/>
    /// </summary>
    public class ListSyncLevelTypeNullableJsonConverter : JsonConverter<ListSyncLevelType?>
    {
        /// <summary>
        /// Returns a ListSyncLevelType from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override ListSyncLevelType? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            if (reader.TokenType == JsonTokenType.Null)
                return null;

            string? rawValue = reader.GetString();

            ListSyncLevelType? result = rawValue == null
                ? null
                : ListSyncLevelTypeValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the ListSyncLevelType to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="listSyncLevelType"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, ListSyncLevelType? listSyncLevelType, JsonSerializerOptions options)
        {
            if (listSyncLevelType.HasValue)
                writer.WriteStringValue(ListSyncLevelTypeValueConverter.ToJsonValue(listSyncLevelType.Value).ToString());
            else
                writer.WriteNullValue();
        }
    }
}
