// <auto-generated>
/*
 * Whisparr
 *
 * Whisparr API docs - The v3 API docs apply to both v2 versions of Whisparr. Some functionality may only be available in v2 of the Whisparr application.
 *
 * The version of the OpenAPI document: 3.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Whisparr2.Net.Client;

namespace Whisparr2.Net.Model
{
    /// <summary>
    /// ManualImportReprocessResource
    /// </summary>
    public partial class ManualImportReprocessResource : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ManualImportReprocessResource" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="path">path</param>
        /// <param name="seriesId">seriesId</param>
        /// <param name="seasonNumber">seasonNumber</param>
        /// <param name="episodes">episodes</param>
        /// <param name="episodeIds">episodeIds</param>
        /// <param name="quality">quality</param>
        /// <param name="languages">languages</param>
        /// <param name="releaseGroup">releaseGroup</param>
        /// <param name="downloadId">downloadId</param>
        /// <param name="customFormats">customFormats</param>
        /// <param name="customFormatScore">customFormatScore</param>
        /// <param name="rejections">rejections</param>
        [JsonConstructor]
        public ManualImportReprocessResource(Option<int?> id = default, Option<string?> path = default, Option<int?> seriesId = default, Option<int?> seasonNumber = default, Option<List<EpisodeResource>?> episodes = default, Option<List<int>?> episodeIds = default, Option<QualityModel?> quality = default, Option<List<Language>?> languages = default, Option<string?> releaseGroup = default, Option<string?> downloadId = default, Option<List<CustomFormatResource>?> customFormats = default, Option<int?> customFormatScore = default, Option<List<Rejection>?> rejections = default)
        {
            IdOption = id;
            PathOption = path;
            SeriesIdOption = seriesId;
            SeasonNumberOption = seasonNumber;
            EpisodesOption = episodes;
            EpisodeIdsOption = episodeIds;
            QualityOption = quality;
            LanguagesOption = languages;
            ReleaseGroupOption = releaseGroup;
            DownloadIdOption = downloadId;
            CustomFormatsOption = customFormats;
            CustomFormatScoreOption = customFormatScore;
            RejectionsOption = rejections;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Id
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> IdOption { get; private set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public int? Id { get { return this.IdOption.Value; } set { this.IdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Path
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> PathOption { get; private set; }

        /// <summary>
        /// Gets or Sets Path
        /// </summary>
        [JsonPropertyName("path")]
        public string? Path { get { return this.PathOption.Value; } set { this.PathOption = new(value); } }

        /// <summary>
        /// Used to track the state of SeriesId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> SeriesIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets SeriesId
        /// </summary>
        [JsonPropertyName("seriesId")]
        public int? SeriesId { get { return this.SeriesIdOption.Value; } set { this.SeriesIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of SeasonNumber
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> SeasonNumberOption { get; private set; }

        /// <summary>
        /// Gets or Sets SeasonNumber
        /// </summary>
        [JsonPropertyName("seasonNumber")]
        public int? SeasonNumber { get { return this.SeasonNumberOption.Value; } set { this.SeasonNumberOption = new(value); } }

        /// <summary>
        /// Used to track the state of Episodes
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<EpisodeResource>?> EpisodesOption { get; private set; }

        /// <summary>
        /// Gets or Sets Episodes
        /// </summary>
        [JsonPropertyName("episodes")]
        public List<EpisodeResource>? Episodes { get { return this.EpisodesOption.Value; } set { this.EpisodesOption = new(value); } }

        /// <summary>
        /// Used to track the state of EpisodeIds
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<int>?> EpisodeIdsOption { get; private set; }

        /// <summary>
        /// Gets or Sets EpisodeIds
        /// </summary>
        [JsonPropertyName("episodeIds")]
        public List<int>? EpisodeIds { get { return this.EpisodeIdsOption.Value; } set { this.EpisodeIdsOption = new(value); } }

        /// <summary>
        /// Used to track the state of Quality
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<QualityModel?> QualityOption { get; private set; }

        /// <summary>
        /// Gets or Sets Quality
        /// </summary>
        [JsonPropertyName("quality")]
        public QualityModel? Quality { get { return this.QualityOption.Value; } set { this.QualityOption = new(value); } }

        /// <summary>
        /// Used to track the state of Languages
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<Language>?> LanguagesOption { get; private set; }

        /// <summary>
        /// Gets or Sets Languages
        /// </summary>
        [JsonPropertyName("languages")]
        public List<Language>? Languages { get { return this.LanguagesOption.Value; } set { this.LanguagesOption = new(value); } }

        /// <summary>
        /// Used to track the state of ReleaseGroup
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ReleaseGroupOption { get; private set; }

        /// <summary>
        /// Gets or Sets ReleaseGroup
        /// </summary>
        [JsonPropertyName("releaseGroup")]
        public string? ReleaseGroup { get { return this.ReleaseGroupOption.Value; } set { this.ReleaseGroupOption = new(value); } }

        /// <summary>
        /// Used to track the state of DownloadId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DownloadIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets DownloadId
        /// </summary>
        [JsonPropertyName("downloadId")]
        public string? DownloadId { get { return this.DownloadIdOption.Value; } set { this.DownloadIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of CustomFormats
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<CustomFormatResource>?> CustomFormatsOption { get; private set; }

        /// <summary>
        /// Gets or Sets CustomFormats
        /// </summary>
        [JsonPropertyName("customFormats")]
        public List<CustomFormatResource>? CustomFormats { get { return this.CustomFormatsOption.Value; } set { this.CustomFormatsOption = new(value); } }

        /// <summary>
        /// Used to track the state of CustomFormatScore
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> CustomFormatScoreOption { get; private set; }

        /// <summary>
        /// Gets or Sets CustomFormatScore
        /// </summary>
        [JsonPropertyName("customFormatScore")]
        public int? CustomFormatScore { get { return this.CustomFormatScoreOption.Value; } set { this.CustomFormatScoreOption = new(value); } }

        /// <summary>
        /// Used to track the state of Rejections
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<Rejection>?> RejectionsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Rejections
        /// </summary>
        [JsonPropertyName("rejections")]
        public List<Rejection>? Rejections { get { return this.RejectionsOption.Value; } set { this.RejectionsOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ManualImportReprocessResource {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Path: ").Append(Path).Append("\n");
            sb.Append("  SeriesId: ").Append(SeriesId).Append("\n");
            sb.Append("  SeasonNumber: ").Append(SeasonNumber).Append("\n");
            sb.Append("  Episodes: ").Append(Episodes).Append("\n");
            sb.Append("  EpisodeIds: ").Append(EpisodeIds).Append("\n");
            sb.Append("  Quality: ").Append(Quality).Append("\n");
            sb.Append("  Languages: ").Append(Languages).Append("\n");
            sb.Append("  ReleaseGroup: ").Append(ReleaseGroup).Append("\n");
            sb.Append("  DownloadId: ").Append(DownloadId).Append("\n");
            sb.Append("  CustomFormats: ").Append(CustomFormats).Append("\n");
            sb.Append("  CustomFormatScore: ").Append(CustomFormatScore).Append("\n");
            sb.Append("  Rejections: ").Append(Rejections).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ManualImportReprocessResource" />
    /// </summary>
    public partial class ManualImportReprocessResourceJsonConverter : JsonConverter<ManualImportReprocessResource>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="ManualImportReprocessResourceJsonConverter" /> class.
        /// </summary>
        public ManualImportReprocessResourceJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="ManualImportReprocessResource" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ManualImportReprocessResource Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> id = default;
            Option<string?> path = default;
            Option<int?> seriesId = default;
            Option<int?> seasonNumber = default;
            Option<List<EpisodeResource>?> episodes = default;
            Option<List<int>?> episodeIds = default;
            Option<QualityModel?> quality = default;
            Option<List<Language>?> languages = default;
            Option<string?> releaseGroup = default;
            Option<string?> downloadId = default;
            Option<List<CustomFormatResource>?> customFormats = default;
            Option<int?> customFormatScore = default;
            Option<List<Rejection>?> rejections = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "path":
                            path = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "seriesId":
                            seriesId = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "seasonNumber":
                            seasonNumber = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "episodes":
                            episodes = new Option<List<EpisodeResource>?>(JsonSerializer.Deserialize<List<EpisodeResource>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "episodeIds":
                            episodeIds = new Option<List<int>?>(JsonSerializer.Deserialize<List<int>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "quality":
                            quality = new Option<QualityModel?>(JsonSerializer.Deserialize<QualityModel>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "languages":
                            languages = new Option<List<Language>?>(JsonSerializer.Deserialize<List<Language>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "releaseGroup":
                            releaseGroup = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "downloadId":
                            downloadId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "customFormats":
                            customFormats = new Option<List<CustomFormatResource>?>(JsonSerializer.Deserialize<List<CustomFormatResource>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "customFormatScore":
                            customFormatScore = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "rejections":
                            rejections = new Option<List<Rejection>?>(JsonSerializer.Deserialize<List<Rejection>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class ManualImportReprocessResource.");

            if (seriesId.IsSet && seriesId.Value == null)
                throw new ArgumentNullException(nameof(seriesId), "Property is not nullable for class ManualImportReprocessResource.");

            if (quality.IsSet && quality.Value == null)
                throw new ArgumentNullException(nameof(quality), "Property is not nullable for class ManualImportReprocessResource.");

            if (customFormatScore.IsSet && customFormatScore.Value == null)
                throw new ArgumentNullException(nameof(customFormatScore), "Property is not nullable for class ManualImportReprocessResource.");

            return new ManualImportReprocessResource(id, path, seriesId, seasonNumber, episodes, episodeIds, quality, languages, releaseGroup, downloadId, customFormats, customFormatScore, rejections);
        }

        /// <summary>
        /// Serializes a <see cref="ManualImportReprocessResource" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="manualImportReprocessResource"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ManualImportReprocessResource manualImportReprocessResource, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, manualImportReprocessResource, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ManualImportReprocessResource" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="manualImportReprocessResource"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ManualImportReprocessResource manualImportReprocessResource, JsonSerializerOptions jsonSerializerOptions)
        {
            if (manualImportReprocessResource.QualityOption.IsSet && manualImportReprocessResource.Quality == null)
                throw new ArgumentNullException(nameof(manualImportReprocessResource.Quality), "Property is required for class ManualImportReprocessResource.");

            if (manualImportReprocessResource.IdOption.IsSet)
                writer.WriteNumber("id", manualImportReprocessResource.IdOption.Value!.Value);

            if (manualImportReprocessResource.PathOption.IsSet)
                if (manualImportReprocessResource.PathOption.Value != null)
                    writer.WriteString("path", manualImportReprocessResource.Path);
                else
                    writer.WriteNull("path");

            if (manualImportReprocessResource.SeriesIdOption.IsSet)
                writer.WriteNumber("seriesId", manualImportReprocessResource.SeriesIdOption.Value!.Value);

            if (manualImportReprocessResource.SeasonNumberOption.IsSet)
                if (manualImportReprocessResource.SeasonNumberOption.Value != null)
                    writer.WriteNumber("seasonNumber", manualImportReprocessResource.SeasonNumberOption.Value!.Value);
                else
                    writer.WriteNull("seasonNumber");

            if (manualImportReprocessResource.EpisodesOption.IsSet)
                if (manualImportReprocessResource.EpisodesOption.Value != null)
                {
                    writer.WritePropertyName("episodes");
                    JsonSerializer.Serialize(writer, manualImportReprocessResource.Episodes, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("episodes");
            if (manualImportReprocessResource.EpisodeIdsOption.IsSet)
                if (manualImportReprocessResource.EpisodeIdsOption.Value != null)
                {
                    writer.WritePropertyName("episodeIds");
                    JsonSerializer.Serialize(writer, manualImportReprocessResource.EpisodeIds, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("episodeIds");
            if (manualImportReprocessResource.QualityOption.IsSet)
            {
                writer.WritePropertyName("quality");
                JsonSerializer.Serialize(writer, manualImportReprocessResource.Quality, jsonSerializerOptions);
            }
            if (manualImportReprocessResource.LanguagesOption.IsSet)
                if (manualImportReprocessResource.LanguagesOption.Value != null)
                {
                    writer.WritePropertyName("languages");
                    JsonSerializer.Serialize(writer, manualImportReprocessResource.Languages, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("languages");
            if (manualImportReprocessResource.ReleaseGroupOption.IsSet)
                if (manualImportReprocessResource.ReleaseGroupOption.Value != null)
                    writer.WriteString("releaseGroup", manualImportReprocessResource.ReleaseGroup);
                else
                    writer.WriteNull("releaseGroup");

            if (manualImportReprocessResource.DownloadIdOption.IsSet)
                if (manualImportReprocessResource.DownloadIdOption.Value != null)
                    writer.WriteString("downloadId", manualImportReprocessResource.DownloadId);
                else
                    writer.WriteNull("downloadId");

            if (manualImportReprocessResource.CustomFormatsOption.IsSet)
                if (manualImportReprocessResource.CustomFormatsOption.Value != null)
                {
                    writer.WritePropertyName("customFormats");
                    JsonSerializer.Serialize(writer, manualImportReprocessResource.CustomFormats, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("customFormats");
            if (manualImportReprocessResource.CustomFormatScoreOption.IsSet)
                writer.WriteNumber("customFormatScore", manualImportReprocessResource.CustomFormatScoreOption.Value!.Value);

            if (manualImportReprocessResource.RejectionsOption.IsSet)
                if (manualImportReprocessResource.RejectionsOption.Value != null)
                {
                    writer.WritePropertyName("rejections");
                    JsonSerializer.Serialize(writer, manualImportReprocessResource.Rejections, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("rejections");
        }
    }
}
