// <auto-generated>
/*
 * Whisparr
 *
 * Whisparr API docs - The v3 API docs apply to both v2 versions of Whisparr. Some functionality may only be available in v2 of the Whisparr application.
 *
 * The version of the OpenAPI document: 3.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Whisparr2.Net.Client;

namespace Whisparr2.Net.Model
{
    /// <summary>
    /// Defines NewItemMonitorTypes
    /// </summary>
    public enum NewItemMonitorTypes
    {
        /// <summary>
        /// Enum All for value: all
        /// </summary>
        All = 1,

        /// <summary>
        /// Enum None for value: none
        /// </summary>
        None = 2
    }

    /// <summary>
    /// Converts <see cref="NewItemMonitorTypes"/> to and from the JSON value
    /// </summary>
    public static class NewItemMonitorTypesValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="NewItemMonitorTypes"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static NewItemMonitorTypes FromString(string value)
        {
            if (value.Equals("all"))
                return NewItemMonitorTypes.All;

            if (value.Equals("none"))
                return NewItemMonitorTypes.None;

            throw new NotImplementedException($"Could not convert value to type NewItemMonitorTypes: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="NewItemMonitorTypes"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static NewItemMonitorTypes? FromStringOrDefault(string value)
        {
            if (value.Equals("all"))
                return NewItemMonitorTypes.All;

            if (value.Equals("none"))
                return NewItemMonitorTypes.None;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="NewItemMonitorTypes"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ToJsonValue(NewItemMonitorTypes value)
        {
            if (value == NewItemMonitorTypes.All)
                return "all";

            if (value == NewItemMonitorTypes.None)
                return "none";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="NewItemMonitorTypes"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class NewItemMonitorTypesJsonConverter : JsonConverter<NewItemMonitorTypes>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override NewItemMonitorTypes Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            NewItemMonitorTypes? result = rawValue == null
                ? null
                : NewItemMonitorTypesValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the NewItemMonitorTypes to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="newItemMonitorTypes"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, NewItemMonitorTypes newItemMonitorTypes, JsonSerializerOptions options)
        {
            writer.WriteStringValue(NewItemMonitorTypesValueConverter.ToJsonValue(newItemMonitorTypes).ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="NewItemMonitorTypes"/>
    /// </summary>
    public class NewItemMonitorTypesNullableJsonConverter : JsonConverter<NewItemMonitorTypes?>
    {
        /// <summary>
        /// Returns a NewItemMonitorTypes from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override NewItemMonitorTypes? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            if (reader.TokenType == JsonTokenType.Null)
                return null;

            string? rawValue = reader.GetString();

            NewItemMonitorTypes? result = rawValue == null
                ? null
                : NewItemMonitorTypesValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the NewItemMonitorTypes to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="newItemMonitorTypes"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, NewItemMonitorTypes? newItemMonitorTypes, JsonSerializerOptions options)
        {
            if (newItemMonitorTypes.HasValue)
                writer.WriteStringValue(NewItemMonitorTypesValueConverter.ToJsonValue(newItemMonitorTypes.Value).ToString());
            else
                writer.WriteNullValue();
        }
    }
}
