// <auto-generated>
/*
 * Whisparr
 *
 * Whisparr API docs - The v3 API docs apply to both v2 versions of Whisparr. Some functionality may only be available in v2 of the Whisparr application.
 *
 * The version of the OpenAPI document: 3.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Whisparr2.Net.Client;

namespace Whisparr2.Net.Model
{
    /// <summary>
    /// ParsedEpisodeInfo
    /// </summary>
    public partial class ParsedEpisodeInfo : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ParsedEpisodeInfo" /> class.
        /// </summary>
        /// <param name="releaseTitle">releaseTitle</param>
        /// <param name="seriesTitle">seriesTitle</param>
        /// <param name="seriesTitleInfo">seriesTitleInfo</param>
        /// <param name="quality">quality</param>
        /// <param name="airDate">airDate</param>
        /// <param name="languages">languages</param>
        /// <param name="releaseGroup">releaseGroup</param>
        /// <param name="releaseHash">releaseHash</param>
        /// <param name="seasonPart">seasonPart</param>
        /// <param name="releaseTokens">releaseTokens</param>
        /// <param name="externalId">externalId</param>
        /// <param name="isDaily">isDaily</param>
        [JsonConstructor]
        public ParsedEpisodeInfo(Option<string?> releaseTitle = default, Option<string?> seriesTitle = default, Option<SeriesTitleInfo?> seriesTitleInfo = default, Option<QualityModel?> quality = default, Option<string?> airDate = default, Option<List<Language>?> languages = default, Option<string?> releaseGroup = default, Option<string?> releaseHash = default, Option<int?> seasonPart = default, Option<string?> releaseTokens = default, Option<string?> externalId = default, Option<bool?> isDaily = default)
        {
            ReleaseTitleOption = releaseTitle;
            SeriesTitleOption = seriesTitle;
            SeriesTitleInfoOption = seriesTitleInfo;
            QualityOption = quality;
            AirDateOption = airDate;
            LanguagesOption = languages;
            ReleaseGroupOption = releaseGroup;
            ReleaseHashOption = releaseHash;
            SeasonPartOption = seasonPart;
            ReleaseTokensOption = releaseTokens;
            ExternalIdOption = externalId;
            IsDailyOption = isDaily;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of ReleaseTitle
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ReleaseTitleOption { get; private set; }

        /// <summary>
        /// Gets or Sets ReleaseTitle
        /// </summary>
        [JsonPropertyName("releaseTitle")]
        public string? ReleaseTitle { get { return this.ReleaseTitleOption.Value; } set { this.ReleaseTitleOption = new(value); } }

        /// <summary>
        /// Used to track the state of SeriesTitle
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SeriesTitleOption { get; private set; }

        /// <summary>
        /// Gets or Sets SeriesTitle
        /// </summary>
        [JsonPropertyName("seriesTitle")]
        public string? SeriesTitle { get { return this.SeriesTitleOption.Value; } set { this.SeriesTitleOption = new(value); } }

        /// <summary>
        /// Used to track the state of SeriesTitleInfo
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<SeriesTitleInfo?> SeriesTitleInfoOption { get; private set; }

        /// <summary>
        /// Gets or Sets SeriesTitleInfo
        /// </summary>
        [JsonPropertyName("seriesTitleInfo")]
        public SeriesTitleInfo? SeriesTitleInfo { get { return this.SeriesTitleInfoOption.Value; } set { this.SeriesTitleInfoOption = new(value); } }

        /// <summary>
        /// Used to track the state of Quality
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<QualityModel?> QualityOption { get; private set; }

        /// <summary>
        /// Gets or Sets Quality
        /// </summary>
        [JsonPropertyName("quality")]
        public QualityModel? Quality { get { return this.QualityOption.Value; } set { this.QualityOption = new(value); } }

        /// <summary>
        /// Used to track the state of AirDate
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> AirDateOption { get; private set; }

        /// <summary>
        /// Gets or Sets AirDate
        /// </summary>
        [JsonPropertyName("airDate")]
        public string? AirDate { get { return this.AirDateOption.Value; } set { this.AirDateOption = new(value); } }

        /// <summary>
        /// Used to track the state of Languages
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<Language>?> LanguagesOption { get; private set; }

        /// <summary>
        /// Gets or Sets Languages
        /// </summary>
        [JsonPropertyName("languages")]
        public List<Language>? Languages { get { return this.LanguagesOption.Value; } set { this.LanguagesOption = new(value); } }

        /// <summary>
        /// Used to track the state of ReleaseGroup
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ReleaseGroupOption { get; private set; }

        /// <summary>
        /// Gets or Sets ReleaseGroup
        /// </summary>
        [JsonPropertyName("releaseGroup")]
        public string? ReleaseGroup { get { return this.ReleaseGroupOption.Value; } set { this.ReleaseGroupOption = new(value); } }

        /// <summary>
        /// Used to track the state of ReleaseHash
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ReleaseHashOption { get; private set; }

        /// <summary>
        /// Gets or Sets ReleaseHash
        /// </summary>
        [JsonPropertyName("releaseHash")]
        public string? ReleaseHash { get { return this.ReleaseHashOption.Value; } set { this.ReleaseHashOption = new(value); } }

        /// <summary>
        /// Used to track the state of SeasonPart
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> SeasonPartOption { get; private set; }

        /// <summary>
        /// Gets or Sets SeasonPart
        /// </summary>
        [JsonPropertyName("seasonPart")]
        public int? SeasonPart { get { return this.SeasonPartOption.Value; } set { this.SeasonPartOption = new(value); } }

        /// <summary>
        /// Used to track the state of ReleaseTokens
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ReleaseTokensOption { get; private set; }

        /// <summary>
        /// Gets or Sets ReleaseTokens
        /// </summary>
        [JsonPropertyName("releaseTokens")]
        public string? ReleaseTokens { get { return this.ReleaseTokensOption.Value; } set { this.ReleaseTokensOption = new(value); } }

        /// <summary>
        /// Used to track the state of ExternalId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ExternalIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets ExternalId
        /// </summary>
        [JsonPropertyName("externalId")]
        public string? ExternalId { get { return this.ExternalIdOption.Value; } set { this.ExternalIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of IsDaily
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> IsDailyOption { get; }

        /// <summary>
        /// Gets or Sets IsDaily
        /// </summary>
        [JsonPropertyName("isDaily")]
        public bool? IsDaily { get { return this.IsDailyOption.Value; } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ParsedEpisodeInfo {\n");
            sb.Append("  ReleaseTitle: ").Append(ReleaseTitle).Append("\n");
            sb.Append("  SeriesTitle: ").Append(SeriesTitle).Append("\n");
            sb.Append("  SeriesTitleInfo: ").Append(SeriesTitleInfo).Append("\n");
            sb.Append("  Quality: ").Append(Quality).Append("\n");
            sb.Append("  AirDate: ").Append(AirDate).Append("\n");
            sb.Append("  Languages: ").Append(Languages).Append("\n");
            sb.Append("  ReleaseGroup: ").Append(ReleaseGroup).Append("\n");
            sb.Append("  ReleaseHash: ").Append(ReleaseHash).Append("\n");
            sb.Append("  SeasonPart: ").Append(SeasonPart).Append("\n");
            sb.Append("  ReleaseTokens: ").Append(ReleaseTokens).Append("\n");
            sb.Append("  ExternalId: ").Append(ExternalId).Append("\n");
            sb.Append("  IsDaily: ").Append(IsDaily).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ParsedEpisodeInfo" />
    /// </summary>
    public partial class ParsedEpisodeInfoJsonConverter : JsonConverter<ParsedEpisodeInfo>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="ParsedEpisodeInfoJsonConverter" /> class.
        /// </summary>
        public ParsedEpisodeInfoJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="ParsedEpisodeInfo" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ParsedEpisodeInfo Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> releaseTitle = default;
            Option<string?> seriesTitle = default;
            Option<SeriesTitleInfo?> seriesTitleInfo = default;
            Option<QualityModel?> quality = default;
            Option<string?> airDate = default;
            Option<List<Language>?> languages = default;
            Option<string?> releaseGroup = default;
            Option<string?> releaseHash = default;
            Option<int?> seasonPart = default;
            Option<string?> releaseTokens = default;
            Option<string?> externalId = default;
            Option<bool?> isDaily = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "releaseTitle":
                            releaseTitle = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "seriesTitle":
                            seriesTitle = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "seriesTitleInfo":
                            seriesTitleInfo = new Option<SeriesTitleInfo?>(JsonSerializer.Deserialize<SeriesTitleInfo>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "quality":
                            quality = new Option<QualityModel?>(JsonSerializer.Deserialize<QualityModel>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "airDate":
                            airDate = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "languages":
                            languages = new Option<List<Language>?>(JsonSerializer.Deserialize<List<Language>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "releaseGroup":
                            releaseGroup = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "releaseHash":
                            releaseHash = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "seasonPart":
                            seasonPart = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "releaseTokens":
                            releaseTokens = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "externalId":
                            externalId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "isDaily":
                            isDaily = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (seriesTitleInfo.IsSet && seriesTitleInfo.Value == null)
                throw new ArgumentNullException(nameof(seriesTitleInfo), "Property is not nullable for class ParsedEpisodeInfo.");

            if (quality.IsSet && quality.Value == null)
                throw new ArgumentNullException(nameof(quality), "Property is not nullable for class ParsedEpisodeInfo.");

            if (seasonPart.IsSet && seasonPart.Value == null)
                throw new ArgumentNullException(nameof(seasonPart), "Property is not nullable for class ParsedEpisodeInfo.");

            if (isDaily.IsSet && isDaily.Value == null)
                throw new ArgumentNullException(nameof(isDaily), "Property is not nullable for class ParsedEpisodeInfo.");

            return new ParsedEpisodeInfo(releaseTitle, seriesTitle, seriesTitleInfo, quality, airDate, languages, releaseGroup, releaseHash, seasonPart, releaseTokens, externalId, isDaily);
        }

        /// <summary>
        /// Serializes a <see cref="ParsedEpisodeInfo" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="parsedEpisodeInfo"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ParsedEpisodeInfo parsedEpisodeInfo, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, parsedEpisodeInfo, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ParsedEpisodeInfo" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="parsedEpisodeInfo"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ParsedEpisodeInfo parsedEpisodeInfo, JsonSerializerOptions jsonSerializerOptions)
        {
            if (parsedEpisodeInfo.SeriesTitleInfoOption.IsSet && parsedEpisodeInfo.SeriesTitleInfo == null)
                throw new ArgumentNullException(nameof(parsedEpisodeInfo.SeriesTitleInfo), "Property is required for class ParsedEpisodeInfo.");

            if (parsedEpisodeInfo.QualityOption.IsSet && parsedEpisodeInfo.Quality == null)
                throw new ArgumentNullException(nameof(parsedEpisodeInfo.Quality), "Property is required for class ParsedEpisodeInfo.");

            if (parsedEpisodeInfo.ReleaseTitleOption.IsSet)
                if (parsedEpisodeInfo.ReleaseTitleOption.Value != null)
                    writer.WriteString("releaseTitle", parsedEpisodeInfo.ReleaseTitle);
                else
                    writer.WriteNull("releaseTitle");

            if (parsedEpisodeInfo.SeriesTitleOption.IsSet)
                if (parsedEpisodeInfo.SeriesTitleOption.Value != null)
                    writer.WriteString("seriesTitle", parsedEpisodeInfo.SeriesTitle);
                else
                    writer.WriteNull("seriesTitle");

            if (parsedEpisodeInfo.SeriesTitleInfoOption.IsSet)
            {
                writer.WritePropertyName("seriesTitleInfo");
                JsonSerializer.Serialize(writer, parsedEpisodeInfo.SeriesTitleInfo, jsonSerializerOptions);
            }
            if (parsedEpisodeInfo.QualityOption.IsSet)
            {
                writer.WritePropertyName("quality");
                JsonSerializer.Serialize(writer, parsedEpisodeInfo.Quality, jsonSerializerOptions);
            }
            if (parsedEpisodeInfo.AirDateOption.IsSet)
                if (parsedEpisodeInfo.AirDateOption.Value != null)
                    writer.WriteString("airDate", parsedEpisodeInfo.AirDate);
                else
                    writer.WriteNull("airDate");

            if (parsedEpisodeInfo.LanguagesOption.IsSet)
                if (parsedEpisodeInfo.LanguagesOption.Value != null)
                {
                    writer.WritePropertyName("languages");
                    JsonSerializer.Serialize(writer, parsedEpisodeInfo.Languages, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("languages");
            if (parsedEpisodeInfo.ReleaseGroupOption.IsSet)
                if (parsedEpisodeInfo.ReleaseGroupOption.Value != null)
                    writer.WriteString("releaseGroup", parsedEpisodeInfo.ReleaseGroup);
                else
                    writer.WriteNull("releaseGroup");

            if (parsedEpisodeInfo.ReleaseHashOption.IsSet)
                if (parsedEpisodeInfo.ReleaseHashOption.Value != null)
                    writer.WriteString("releaseHash", parsedEpisodeInfo.ReleaseHash);
                else
                    writer.WriteNull("releaseHash");

            if (parsedEpisodeInfo.SeasonPartOption.IsSet)
                writer.WriteNumber("seasonPart", parsedEpisodeInfo.SeasonPartOption.Value!.Value);

            if (parsedEpisodeInfo.ReleaseTokensOption.IsSet)
                if (parsedEpisodeInfo.ReleaseTokensOption.Value != null)
                    writer.WriteString("releaseTokens", parsedEpisodeInfo.ReleaseTokens);
                else
                    writer.WriteNull("releaseTokens");

            if (parsedEpisodeInfo.ExternalIdOption.IsSet)
                if (parsedEpisodeInfo.ExternalIdOption.Value != null)
                    writer.WriteString("externalId", parsedEpisodeInfo.ExternalId);
                else
                    writer.WriteNull("externalId");

            if (parsedEpisodeInfo.IsDailyOption.IsSet)
                writer.WriteBoolean("isDaily", parsedEpisodeInfo.IsDailyOption.Value!.Value);
        }
    }
}
