// <auto-generated>
/*
 * Whisparr
 *
 * Whisparr API docs - The v3 API docs apply to both v2 versions of Whisparr. Some functionality may only be available in v2 of the Whisparr application.
 *
 * The version of the OpenAPI document: 3.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Whisparr2.Net.Client;

namespace Whisparr2.Net.Model
{
    /// <summary>
    /// ReleaseEpisodeResource
    /// </summary>
    public partial class ReleaseEpisodeResource : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ReleaseEpisodeResource" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="seasonNumber">seasonNumber</param>
        /// <param name="episodeNumber">episodeNumber</param>
        /// <param name="absoluteEpisodeNumber">absoluteEpisodeNumber</param>
        /// <param name="title">title</param>
        [JsonConstructor]
        public ReleaseEpisodeResource(Option<int?> id = default, Option<int?> seasonNumber = default, Option<int?> episodeNumber = default, Option<int?> absoluteEpisodeNumber = default, Option<string?> title = default)
        {
            IdOption = id;
            SeasonNumberOption = seasonNumber;
            EpisodeNumberOption = episodeNumber;
            AbsoluteEpisodeNumberOption = absoluteEpisodeNumber;
            TitleOption = title;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Id
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> IdOption { get; private set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public int? Id { get { return this.IdOption.Value; } set { this.IdOption = new(value); } }

        /// <summary>
        /// Used to track the state of SeasonNumber
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> SeasonNumberOption { get; private set; }

        /// <summary>
        /// Gets or Sets SeasonNumber
        /// </summary>
        [JsonPropertyName("seasonNumber")]
        public int? SeasonNumber { get { return this.SeasonNumberOption.Value; } set { this.SeasonNumberOption = new(value); } }

        /// <summary>
        /// Used to track the state of EpisodeNumber
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> EpisodeNumberOption { get; private set; }

        /// <summary>
        /// Gets or Sets EpisodeNumber
        /// </summary>
        [JsonPropertyName("episodeNumber")]
        public int? EpisodeNumber { get { return this.EpisodeNumberOption.Value; } set { this.EpisodeNumberOption = new(value); } }

        /// <summary>
        /// Used to track the state of AbsoluteEpisodeNumber
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> AbsoluteEpisodeNumberOption { get; private set; }

        /// <summary>
        /// Gets or Sets AbsoluteEpisodeNumber
        /// </summary>
        [JsonPropertyName("absoluteEpisodeNumber")]
        public int? AbsoluteEpisodeNumber { get { return this.AbsoluteEpisodeNumberOption.Value; } set { this.AbsoluteEpisodeNumberOption = new(value); } }

        /// <summary>
        /// Used to track the state of Title
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TitleOption { get; private set; }

        /// <summary>
        /// Gets or Sets Title
        /// </summary>
        [JsonPropertyName("title")]
        public string? Title { get { return this.TitleOption.Value; } set { this.TitleOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ReleaseEpisodeResource {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  SeasonNumber: ").Append(SeasonNumber).Append("\n");
            sb.Append("  EpisodeNumber: ").Append(EpisodeNumber).Append("\n");
            sb.Append("  AbsoluteEpisodeNumber: ").Append(AbsoluteEpisodeNumber).Append("\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ReleaseEpisodeResource" />
    /// </summary>
    public partial class ReleaseEpisodeResourceJsonConverter : JsonConverter<ReleaseEpisodeResource>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="ReleaseEpisodeResourceJsonConverter" /> class.
        /// </summary>
        public ReleaseEpisodeResourceJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="ReleaseEpisodeResource" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ReleaseEpisodeResource Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> id = default;
            Option<int?> seasonNumber = default;
            Option<int?> episodeNumber = default;
            Option<int?> absoluteEpisodeNumber = default;
            Option<string?> title = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "seasonNumber":
                            seasonNumber = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "episodeNumber":
                            episodeNumber = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "absoluteEpisodeNumber":
                            absoluteEpisodeNumber = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "title":
                            title = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class ReleaseEpisodeResource.");

            if (seasonNumber.IsSet && seasonNumber.Value == null)
                throw new ArgumentNullException(nameof(seasonNumber), "Property is not nullable for class ReleaseEpisodeResource.");

            if (episodeNumber.IsSet && episodeNumber.Value == null)
                throw new ArgumentNullException(nameof(episodeNumber), "Property is not nullable for class ReleaseEpisodeResource.");

            return new ReleaseEpisodeResource(id, seasonNumber, episodeNumber, absoluteEpisodeNumber, title);
        }

        /// <summary>
        /// Serializes a <see cref="ReleaseEpisodeResource" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="releaseEpisodeResource"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ReleaseEpisodeResource releaseEpisodeResource, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, releaseEpisodeResource, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ReleaseEpisodeResource" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="releaseEpisodeResource"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ReleaseEpisodeResource releaseEpisodeResource, JsonSerializerOptions jsonSerializerOptions)
        {
            if (releaseEpisodeResource.IdOption.IsSet)
                writer.WriteNumber("id", releaseEpisodeResource.IdOption.Value!.Value);

            if (releaseEpisodeResource.SeasonNumberOption.IsSet)
                writer.WriteNumber("seasonNumber", releaseEpisodeResource.SeasonNumberOption.Value!.Value);

            if (releaseEpisodeResource.EpisodeNumberOption.IsSet)
                writer.WriteNumber("episodeNumber", releaseEpisodeResource.EpisodeNumberOption.Value!.Value);

            if (releaseEpisodeResource.AbsoluteEpisodeNumberOption.IsSet)
                if (releaseEpisodeResource.AbsoluteEpisodeNumberOption.Value != null)
                    writer.WriteNumber("absoluteEpisodeNumber", releaseEpisodeResource.AbsoluteEpisodeNumberOption.Value!.Value);
                else
                    writer.WriteNull("absoluteEpisodeNumber");

            if (releaseEpisodeResource.TitleOption.IsSet)
                if (releaseEpisodeResource.TitleOption.Value != null)
                    writer.WriteString("title", releaseEpisodeResource.Title);
                else
                    writer.WriteNull("title");
        }
    }
}
