// <auto-generated>
/*
 * Whisparr
 *
 * Whisparr API docs - The v3 API docs apply to both v2 versions of Whisparr. Some functionality may only be available in v2 of the Whisparr application.
 *
 * The version of the OpenAPI document: 3.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Whisparr2.Net.Client;

namespace Whisparr2.Net.Model
{
    /// <summary>
    /// SeasonPassSeriesResource
    /// </summary>
    public partial class SeasonPassSeriesResource : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SeasonPassSeriesResource" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="monitored">monitored</param>
        /// <param name="seasons">seasons</param>
        [JsonConstructor]
        public SeasonPassSeriesResource(Option<int?> id = default, Option<bool?> monitored = default, Option<List<SeasonResource>?> seasons = default)
        {
            IdOption = id;
            MonitoredOption = monitored;
            SeasonsOption = seasons;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Id
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> IdOption { get; private set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public int? Id { get { return this.IdOption.Value; } set { this.IdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Monitored
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> MonitoredOption { get; private set; }

        /// <summary>
        /// Gets or Sets Monitored
        /// </summary>
        [JsonPropertyName("monitored")]
        public bool? Monitored { get { return this.MonitoredOption.Value; } set { this.MonitoredOption = new(value); } }

        /// <summary>
        /// Used to track the state of Seasons
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<SeasonResource>?> SeasonsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Seasons
        /// </summary>
        [JsonPropertyName("seasons")]
        public List<SeasonResource>? Seasons { get { return this.SeasonsOption.Value; } set { this.SeasonsOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SeasonPassSeriesResource {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Monitored: ").Append(Monitored).Append("\n");
            sb.Append("  Seasons: ").Append(Seasons).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SeasonPassSeriesResource" />
    /// </summary>
    public partial class SeasonPassSeriesResourceJsonConverter : JsonConverter<SeasonPassSeriesResource>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="SeasonPassSeriesResourceJsonConverter" /> class.
        /// </summary>
        public SeasonPassSeriesResourceJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="SeasonPassSeriesResource" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override SeasonPassSeriesResource Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> id = default;
            Option<bool?> monitored = default;
            Option<List<SeasonResource>?> seasons = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "monitored":
                            monitored = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "seasons":
                            seasons = new Option<List<SeasonResource>?>(JsonSerializer.Deserialize<List<SeasonResource>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class SeasonPassSeriesResource.");

            return new SeasonPassSeriesResource(id, monitored, seasons);
        }

        /// <summary>
        /// Serializes a <see cref="SeasonPassSeriesResource" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="seasonPassSeriesResource"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, SeasonPassSeriesResource seasonPassSeriesResource, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, seasonPassSeriesResource, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="SeasonPassSeriesResource" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="seasonPassSeriesResource"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, SeasonPassSeriesResource seasonPassSeriesResource, JsonSerializerOptions jsonSerializerOptions)
        {
            if (seasonPassSeriesResource.IdOption.IsSet)
                writer.WriteNumber("id", seasonPassSeriesResource.IdOption.Value!.Value);

            if (seasonPassSeriesResource.MonitoredOption.IsSet)
                if (seasonPassSeriesResource.MonitoredOption.Value != null)
                    writer.WriteBoolean("monitored", seasonPassSeriesResource.MonitoredOption.Value!.Value);
                else
                    writer.WriteNull("monitored");

            if (seasonPassSeriesResource.SeasonsOption.IsSet)
                if (seasonPassSeriesResource.SeasonsOption.Value != null)
                {
                    writer.WritePropertyName("seasons");
                    JsonSerializer.Serialize(writer, seasonPassSeriesResource.Seasons, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("seasons");
        }
    }
}
