// <auto-generated>
/*
 * Whisparr
 *
 * Whisparr API docs - The v3 API docs apply to both v2 versions of Whisparr. Some functionality may only be available in v2 of the Whisparr application.
 *
 * The version of the OpenAPI document: 3.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Whisparr2.Net.Client;

namespace Whisparr2.Net.Model
{
    /// <summary>
    /// Defines SeriesStatusType
    /// </summary>
    public enum SeriesStatusType
    {
        /// <summary>
        /// Enum Continuing for value: continuing
        /// </summary>
        Continuing = 1,

        /// <summary>
        /// Enum Ended for value: ended
        /// </summary>
        Ended = 2,

        /// <summary>
        /// Enum Upcoming for value: upcoming
        /// </summary>
        Upcoming = 3,

        /// <summary>
        /// Enum Deleted for value: deleted
        /// </summary>
        Deleted = 4
    }

    /// <summary>
    /// Converts <see cref="SeriesStatusType"/> to and from the JSON value
    /// </summary>
    public static class SeriesStatusTypeValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="SeriesStatusType"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static SeriesStatusType FromString(string value)
        {
            if (value.Equals("continuing"))
                return SeriesStatusType.Continuing;

            if (value.Equals("ended"))
                return SeriesStatusType.Ended;

            if (value.Equals("upcoming"))
                return SeriesStatusType.Upcoming;

            if (value.Equals("deleted"))
                return SeriesStatusType.Deleted;

            throw new NotImplementedException($"Could not convert value to type SeriesStatusType: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="SeriesStatusType"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static SeriesStatusType? FromStringOrDefault(string value)
        {
            if (value.Equals("continuing"))
                return SeriesStatusType.Continuing;

            if (value.Equals("ended"))
                return SeriesStatusType.Ended;

            if (value.Equals("upcoming"))
                return SeriesStatusType.Upcoming;

            if (value.Equals("deleted"))
                return SeriesStatusType.Deleted;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="SeriesStatusType"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ToJsonValue(SeriesStatusType value)
        {
            if (value == SeriesStatusType.Continuing)
                return "continuing";

            if (value == SeriesStatusType.Ended)
                return "ended";

            if (value == SeriesStatusType.Upcoming)
                return "upcoming";

            if (value == SeriesStatusType.Deleted)
                return "deleted";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SeriesStatusType"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class SeriesStatusTypeJsonConverter : JsonConverter<SeriesStatusType>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override SeriesStatusType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            SeriesStatusType? result = rawValue == null
                ? null
                : SeriesStatusTypeValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the SeriesStatusType to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="seriesStatusType"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, SeriesStatusType seriesStatusType, JsonSerializerOptions options)
        {
            writer.WriteStringValue(SeriesStatusTypeValueConverter.ToJsonValue(seriesStatusType).ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SeriesStatusType"/>
    /// </summary>
    public class SeriesStatusTypeNullableJsonConverter : JsonConverter<SeriesStatusType?>
    {
        /// <summary>
        /// Returns a SeriesStatusType from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override SeriesStatusType? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            if (reader.TokenType == JsonTokenType.Null)
                return null;

            string? rawValue = reader.GetString();

            SeriesStatusType? result = rawValue == null
                ? null
                : SeriesStatusTypeValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the SeriesStatusType to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="seriesStatusType"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, SeriesStatusType? seriesStatusType, JsonSerializerOptions options)
        {
            if (seriesStatusType.HasValue)
                writer.WriteStringValue(SeriesStatusTypeValueConverter.ToJsonValue(seriesStatusType.Value).ToString());
            else
                writer.WriteNullValue();
        }
    }
}
