// <auto-generated>
/*
 * Whisparr
 *
 * Whisparr API docs - The v3 API docs apply to both v2 versions of Whisparr. Some functionality may only be available in v2 of the Whisparr application.
 *
 * The version of the OpenAPI document: 3.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Whisparr2.Net.Client;

namespace Whisparr2.Net.Model
{
    /// <summary>
    /// SeriesStatisticsResource
    /// </summary>
    public partial class SeriesStatisticsResource : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SeriesStatisticsResource" /> class.
        /// </summary>
        /// <param name="seasonCount">seasonCount</param>
        /// <param name="episodeFileCount">episodeFileCount</param>
        /// <param name="episodeCount">episodeCount</param>
        /// <param name="totalEpisodeCount">totalEpisodeCount</param>
        /// <param name="sizeOnDisk">sizeOnDisk</param>
        /// <param name="releaseGroups">releaseGroups</param>
        /// <param name="percentOfEpisodes">percentOfEpisodes</param>
        [JsonConstructor]
        public SeriesStatisticsResource(Option<int?> seasonCount = default, Option<int?> episodeFileCount = default, Option<int?> episodeCount = default, Option<int?> totalEpisodeCount = default, Option<long?> sizeOnDisk = default, Option<List<string>?> releaseGroups = default, Option<double?> percentOfEpisodes = default)
        {
            SeasonCountOption = seasonCount;
            EpisodeFileCountOption = episodeFileCount;
            EpisodeCountOption = episodeCount;
            TotalEpisodeCountOption = totalEpisodeCount;
            SizeOnDiskOption = sizeOnDisk;
            ReleaseGroupsOption = releaseGroups;
            PercentOfEpisodesOption = percentOfEpisodes;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of SeasonCount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> SeasonCountOption { get; private set; }

        /// <summary>
        /// Gets or Sets SeasonCount
        /// </summary>
        [JsonPropertyName("seasonCount")]
        public int? SeasonCount { get { return this.SeasonCountOption.Value; } set { this.SeasonCountOption = new(value); } }

        /// <summary>
        /// Used to track the state of EpisodeFileCount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> EpisodeFileCountOption { get; private set; }

        /// <summary>
        /// Gets or Sets EpisodeFileCount
        /// </summary>
        [JsonPropertyName("episodeFileCount")]
        public int? EpisodeFileCount { get { return this.EpisodeFileCountOption.Value; } set { this.EpisodeFileCountOption = new(value); } }

        /// <summary>
        /// Used to track the state of EpisodeCount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> EpisodeCountOption { get; private set; }

        /// <summary>
        /// Gets or Sets EpisodeCount
        /// </summary>
        [JsonPropertyName("episodeCount")]
        public int? EpisodeCount { get { return this.EpisodeCountOption.Value; } set { this.EpisodeCountOption = new(value); } }

        /// <summary>
        /// Used to track the state of TotalEpisodeCount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> TotalEpisodeCountOption { get; private set; }

        /// <summary>
        /// Gets or Sets TotalEpisodeCount
        /// </summary>
        [JsonPropertyName("totalEpisodeCount")]
        public int? TotalEpisodeCount { get { return this.TotalEpisodeCountOption.Value; } set { this.TotalEpisodeCountOption = new(value); } }

        /// <summary>
        /// Used to track the state of SizeOnDisk
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<long?> SizeOnDiskOption { get; private set; }

        /// <summary>
        /// Gets or Sets SizeOnDisk
        /// </summary>
        [JsonPropertyName("sizeOnDisk")]
        public long? SizeOnDisk { get { return this.SizeOnDiskOption.Value; } set { this.SizeOnDiskOption = new(value); } }

        /// <summary>
        /// Used to track the state of ReleaseGroups
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<string>?> ReleaseGroupsOption { get; private set; }

        /// <summary>
        /// Gets or Sets ReleaseGroups
        /// </summary>
        [JsonPropertyName("releaseGroups")]
        public List<string>? ReleaseGroups { get { return this.ReleaseGroupsOption.Value; } set { this.ReleaseGroupsOption = new(value); } }

        /// <summary>
        /// Used to track the state of PercentOfEpisodes
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<double?> PercentOfEpisodesOption { get; }

        /// <summary>
        /// Gets or Sets PercentOfEpisodes
        /// </summary>
        [JsonPropertyName("percentOfEpisodes")]
        public double? PercentOfEpisodes { get { return this.PercentOfEpisodesOption.Value; } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SeriesStatisticsResource {\n");
            sb.Append("  SeasonCount: ").Append(SeasonCount).Append("\n");
            sb.Append("  EpisodeFileCount: ").Append(EpisodeFileCount).Append("\n");
            sb.Append("  EpisodeCount: ").Append(EpisodeCount).Append("\n");
            sb.Append("  TotalEpisodeCount: ").Append(TotalEpisodeCount).Append("\n");
            sb.Append("  SizeOnDisk: ").Append(SizeOnDisk).Append("\n");
            sb.Append("  ReleaseGroups: ").Append(ReleaseGroups).Append("\n");
            sb.Append("  PercentOfEpisodes: ").Append(PercentOfEpisodes).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SeriesStatisticsResource" />
    /// </summary>
    public partial class SeriesStatisticsResourceJsonConverter : JsonConverter<SeriesStatisticsResource>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="SeriesStatisticsResourceJsonConverter" /> class.
        /// </summary>
        public SeriesStatisticsResourceJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="SeriesStatisticsResource" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override SeriesStatisticsResource Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> seasonCount = default;
            Option<int?> episodeFileCount = default;
            Option<int?> episodeCount = default;
            Option<int?> totalEpisodeCount = default;
            Option<long?> sizeOnDisk = default;
            Option<List<string>?> releaseGroups = default;
            Option<double?> percentOfEpisodes = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "seasonCount":
                            seasonCount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "episodeFileCount":
                            episodeFileCount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "episodeCount":
                            episodeCount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "totalEpisodeCount":
                            totalEpisodeCount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "sizeOnDisk":
                            sizeOnDisk = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "releaseGroups":
                            releaseGroups = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "percentOfEpisodes":
                            percentOfEpisodes = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (seasonCount.IsSet && seasonCount.Value == null)
                throw new ArgumentNullException(nameof(seasonCount), "Property is not nullable for class SeriesStatisticsResource.");

            if (episodeFileCount.IsSet && episodeFileCount.Value == null)
                throw new ArgumentNullException(nameof(episodeFileCount), "Property is not nullable for class SeriesStatisticsResource.");

            if (episodeCount.IsSet && episodeCount.Value == null)
                throw new ArgumentNullException(nameof(episodeCount), "Property is not nullable for class SeriesStatisticsResource.");

            if (totalEpisodeCount.IsSet && totalEpisodeCount.Value == null)
                throw new ArgumentNullException(nameof(totalEpisodeCount), "Property is not nullable for class SeriesStatisticsResource.");

            if (sizeOnDisk.IsSet && sizeOnDisk.Value == null)
                throw new ArgumentNullException(nameof(sizeOnDisk), "Property is not nullable for class SeriesStatisticsResource.");

            if (percentOfEpisodes.IsSet && percentOfEpisodes.Value == null)
                throw new ArgumentNullException(nameof(percentOfEpisodes), "Property is not nullable for class SeriesStatisticsResource.");

            return new SeriesStatisticsResource(seasonCount, episodeFileCount, episodeCount, totalEpisodeCount, sizeOnDisk, releaseGroups, percentOfEpisodes);
        }

        /// <summary>
        /// Serializes a <see cref="SeriesStatisticsResource" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="seriesStatisticsResource"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, SeriesStatisticsResource seriesStatisticsResource, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, seriesStatisticsResource, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="SeriesStatisticsResource" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="seriesStatisticsResource"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, SeriesStatisticsResource seriesStatisticsResource, JsonSerializerOptions jsonSerializerOptions)
        {
            if (seriesStatisticsResource.SeasonCountOption.IsSet)
                writer.WriteNumber("seasonCount", seriesStatisticsResource.SeasonCountOption.Value!.Value);

            if (seriesStatisticsResource.EpisodeFileCountOption.IsSet)
                writer.WriteNumber("episodeFileCount", seriesStatisticsResource.EpisodeFileCountOption.Value!.Value);

            if (seriesStatisticsResource.EpisodeCountOption.IsSet)
                writer.WriteNumber("episodeCount", seriesStatisticsResource.EpisodeCountOption.Value!.Value);

            if (seriesStatisticsResource.TotalEpisodeCountOption.IsSet)
                writer.WriteNumber("totalEpisodeCount", seriesStatisticsResource.TotalEpisodeCountOption.Value!.Value);

            if (seriesStatisticsResource.SizeOnDiskOption.IsSet)
                writer.WriteNumber("sizeOnDisk", seriesStatisticsResource.SizeOnDiskOption.Value!.Value);

            if (seriesStatisticsResource.ReleaseGroupsOption.IsSet)
                if (seriesStatisticsResource.ReleaseGroupsOption.Value != null)
                {
                    writer.WritePropertyName("releaseGroups");
                    JsonSerializer.Serialize(writer, seriesStatisticsResource.ReleaseGroups, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("releaseGroups");
            if (seriesStatisticsResource.PercentOfEpisodesOption.IsSet)
                writer.WriteNumber("percentOfEpisodes", seriesStatisticsResource.PercentOfEpisodesOption.Value!.Value);
        }
    }
}
