// <auto-generated>
/*
 * Whisparr
 *
 * Whisparr API docs - The v3 API docs apply to both v2 versions of Whisparr. Some functionality may only be available in v2 of the Whisparr application.
 *
 * The version of the OpenAPI document: 3.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Whisparr2.Net.Client;

namespace Whisparr2.Net.Model
{
    /// <summary>
    /// UiConfigResource
    /// </summary>
    public partial class UiConfigResource : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UiConfigResource" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="firstDayOfWeek">firstDayOfWeek</param>
        /// <param name="calendarWeekColumnHeader">calendarWeekColumnHeader</param>
        /// <param name="shortDateFormat">shortDateFormat</param>
        /// <param name="longDateFormat">longDateFormat</param>
        /// <param name="timeFormat">timeFormat</param>
        /// <param name="showRelativeDates">showRelativeDates</param>
        /// <param name="enableColorImpairedMode">enableColorImpairedMode</param>
        /// <param name="theme">theme</param>
        /// <param name="uiLanguage">uiLanguage</param>
        [JsonConstructor]
        public UiConfigResource(Option<int?> id = default, Option<int?> firstDayOfWeek = default, Option<string?> calendarWeekColumnHeader = default, Option<string?> shortDateFormat = default, Option<string?> longDateFormat = default, Option<string?> timeFormat = default, Option<bool?> showRelativeDates = default, Option<bool?> enableColorImpairedMode = default, Option<string?> theme = default, Option<int?> uiLanguage = default)
        {
            IdOption = id;
            FirstDayOfWeekOption = firstDayOfWeek;
            CalendarWeekColumnHeaderOption = calendarWeekColumnHeader;
            ShortDateFormatOption = shortDateFormat;
            LongDateFormatOption = longDateFormat;
            TimeFormatOption = timeFormat;
            ShowRelativeDatesOption = showRelativeDates;
            EnableColorImpairedModeOption = enableColorImpairedMode;
            ThemeOption = theme;
            UiLanguageOption = uiLanguage;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Id
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> IdOption { get; private set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public int? Id { get { return this.IdOption.Value; } set { this.IdOption = new(value); } }

        /// <summary>
        /// Used to track the state of FirstDayOfWeek
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> FirstDayOfWeekOption { get; private set; }

        /// <summary>
        /// Gets or Sets FirstDayOfWeek
        /// </summary>
        [JsonPropertyName("firstDayOfWeek")]
        public int? FirstDayOfWeek { get { return this.FirstDayOfWeekOption.Value; } set { this.FirstDayOfWeekOption = new(value); } }

        /// <summary>
        /// Used to track the state of CalendarWeekColumnHeader
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CalendarWeekColumnHeaderOption { get; private set; }

        /// <summary>
        /// Gets or Sets CalendarWeekColumnHeader
        /// </summary>
        [JsonPropertyName("calendarWeekColumnHeader")]
        public string? CalendarWeekColumnHeader { get { return this.CalendarWeekColumnHeaderOption.Value; } set { this.CalendarWeekColumnHeaderOption = new(value); } }

        /// <summary>
        /// Used to track the state of ShortDateFormat
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ShortDateFormatOption { get; private set; }

        /// <summary>
        /// Gets or Sets ShortDateFormat
        /// </summary>
        [JsonPropertyName("shortDateFormat")]
        public string? ShortDateFormat { get { return this.ShortDateFormatOption.Value; } set { this.ShortDateFormatOption = new(value); } }

        /// <summary>
        /// Used to track the state of LongDateFormat
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> LongDateFormatOption { get; private set; }

        /// <summary>
        /// Gets or Sets LongDateFormat
        /// </summary>
        [JsonPropertyName("longDateFormat")]
        public string? LongDateFormat { get { return this.LongDateFormatOption.Value; } set { this.LongDateFormatOption = new(value); } }

        /// <summary>
        /// Used to track the state of TimeFormat
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TimeFormatOption { get; private set; }

        /// <summary>
        /// Gets or Sets TimeFormat
        /// </summary>
        [JsonPropertyName("timeFormat")]
        public string? TimeFormat { get { return this.TimeFormatOption.Value; } set { this.TimeFormatOption = new(value); } }

        /// <summary>
        /// Used to track the state of ShowRelativeDates
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> ShowRelativeDatesOption { get; private set; }

        /// <summary>
        /// Gets or Sets ShowRelativeDates
        /// </summary>
        [JsonPropertyName("showRelativeDates")]
        public bool? ShowRelativeDates { get { return this.ShowRelativeDatesOption.Value; } set { this.ShowRelativeDatesOption = new(value); } }

        /// <summary>
        /// Used to track the state of EnableColorImpairedMode
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> EnableColorImpairedModeOption { get; private set; }

        /// <summary>
        /// Gets or Sets EnableColorImpairedMode
        /// </summary>
        [JsonPropertyName("enableColorImpairedMode")]
        public bool? EnableColorImpairedMode { get { return this.EnableColorImpairedModeOption.Value; } set { this.EnableColorImpairedModeOption = new(value); } }

        /// <summary>
        /// Used to track the state of Theme
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ThemeOption { get; private set; }

        /// <summary>
        /// Gets or Sets Theme
        /// </summary>
        [JsonPropertyName("theme")]
        public string? Theme { get { return this.ThemeOption.Value; } set { this.ThemeOption = new(value); } }

        /// <summary>
        /// Used to track the state of UiLanguage
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> UiLanguageOption { get; private set; }

        /// <summary>
        /// Gets or Sets UiLanguage
        /// </summary>
        [JsonPropertyName("uiLanguage")]
        public int? UiLanguage { get { return this.UiLanguageOption.Value; } set { this.UiLanguageOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UiConfigResource {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  FirstDayOfWeek: ").Append(FirstDayOfWeek).Append("\n");
            sb.Append("  CalendarWeekColumnHeader: ").Append(CalendarWeekColumnHeader).Append("\n");
            sb.Append("  ShortDateFormat: ").Append(ShortDateFormat).Append("\n");
            sb.Append("  LongDateFormat: ").Append(LongDateFormat).Append("\n");
            sb.Append("  TimeFormat: ").Append(TimeFormat).Append("\n");
            sb.Append("  ShowRelativeDates: ").Append(ShowRelativeDates).Append("\n");
            sb.Append("  EnableColorImpairedMode: ").Append(EnableColorImpairedMode).Append("\n");
            sb.Append("  Theme: ").Append(Theme).Append("\n");
            sb.Append("  UiLanguage: ").Append(UiLanguage).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="UiConfigResource" />
    /// </summary>
    public partial class UiConfigResourceJsonConverter : JsonConverter<UiConfigResource>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="UiConfigResourceJsonConverter" /> class.
        /// </summary>
        public UiConfigResourceJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="UiConfigResource" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override UiConfigResource Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> id = default;
            Option<int?> firstDayOfWeek = default;
            Option<string?> calendarWeekColumnHeader = default;
            Option<string?> shortDateFormat = default;
            Option<string?> longDateFormat = default;
            Option<string?> timeFormat = default;
            Option<bool?> showRelativeDates = default;
            Option<bool?> enableColorImpairedMode = default;
            Option<string?> theme = default;
            Option<int?> uiLanguage = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "firstDayOfWeek":
                            firstDayOfWeek = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "calendarWeekColumnHeader":
                            calendarWeekColumnHeader = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "shortDateFormat":
                            shortDateFormat = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "longDateFormat":
                            longDateFormat = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "timeFormat":
                            timeFormat = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "showRelativeDates":
                            showRelativeDates = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "enableColorImpairedMode":
                            enableColorImpairedMode = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "theme":
                            theme = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "uiLanguage":
                            uiLanguage = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class UiConfigResource.");

            if (firstDayOfWeek.IsSet && firstDayOfWeek.Value == null)
                throw new ArgumentNullException(nameof(firstDayOfWeek), "Property is not nullable for class UiConfigResource.");

            if (showRelativeDates.IsSet && showRelativeDates.Value == null)
                throw new ArgumentNullException(nameof(showRelativeDates), "Property is not nullable for class UiConfigResource.");

            if (enableColorImpairedMode.IsSet && enableColorImpairedMode.Value == null)
                throw new ArgumentNullException(nameof(enableColorImpairedMode), "Property is not nullable for class UiConfigResource.");

            if (uiLanguage.IsSet && uiLanguage.Value == null)
                throw new ArgumentNullException(nameof(uiLanguage), "Property is not nullable for class UiConfigResource.");

            return new UiConfigResource(id, firstDayOfWeek, calendarWeekColumnHeader, shortDateFormat, longDateFormat, timeFormat, showRelativeDates, enableColorImpairedMode, theme, uiLanguage);
        }

        /// <summary>
        /// Serializes a <see cref="UiConfigResource" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="uiConfigResource"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, UiConfigResource uiConfigResource, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, uiConfigResource, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="UiConfigResource" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="uiConfigResource"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, UiConfigResource uiConfigResource, JsonSerializerOptions jsonSerializerOptions)
        {
            if (uiConfigResource.IdOption.IsSet)
                writer.WriteNumber("id", uiConfigResource.IdOption.Value!.Value);

            if (uiConfigResource.FirstDayOfWeekOption.IsSet)
                writer.WriteNumber("firstDayOfWeek", uiConfigResource.FirstDayOfWeekOption.Value!.Value);

            if (uiConfigResource.CalendarWeekColumnHeaderOption.IsSet)
                if (uiConfigResource.CalendarWeekColumnHeaderOption.Value != null)
                    writer.WriteString("calendarWeekColumnHeader", uiConfigResource.CalendarWeekColumnHeader);
                else
                    writer.WriteNull("calendarWeekColumnHeader");

            if (uiConfigResource.ShortDateFormatOption.IsSet)
                if (uiConfigResource.ShortDateFormatOption.Value != null)
                    writer.WriteString("shortDateFormat", uiConfigResource.ShortDateFormat);
                else
                    writer.WriteNull("shortDateFormat");

            if (uiConfigResource.LongDateFormatOption.IsSet)
                if (uiConfigResource.LongDateFormatOption.Value != null)
                    writer.WriteString("longDateFormat", uiConfigResource.LongDateFormat);
                else
                    writer.WriteNull("longDateFormat");

            if (uiConfigResource.TimeFormatOption.IsSet)
                if (uiConfigResource.TimeFormatOption.Value != null)
                    writer.WriteString("timeFormat", uiConfigResource.TimeFormat);
                else
                    writer.WriteNull("timeFormat");

            if (uiConfigResource.ShowRelativeDatesOption.IsSet)
                writer.WriteBoolean("showRelativeDates", uiConfigResource.ShowRelativeDatesOption.Value!.Value);

            if (uiConfigResource.EnableColorImpairedModeOption.IsSet)
                writer.WriteBoolean("enableColorImpairedMode", uiConfigResource.EnableColorImpairedModeOption.Value!.Value);

            if (uiConfigResource.ThemeOption.IsSet)
                if (uiConfigResource.ThemeOption.Value != null)
                    writer.WriteString("theme", uiConfigResource.Theme);
                else
                    writer.WriteNull("theme");

            if (uiConfigResource.UiLanguageOption.IsSet)
                writer.WriteNumber("uiLanguage", uiConfigResource.UiLanguageOption.Value!.Value);
        }
    }
}
